import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const out=new URL('./outputs/financial-model/',import.meta.url).pathname;
const root=new URL('./',import.meta.url).pathname;
const cases=[['保守',[4,6,8,10,12,14,16,18,20,20,22,22,24,24,24,26,26,26,28,28,28,30,30,30,30,30,30,30,30,30,30,30]],['基准',[8,12,16,20,24,28,32,36,40,44,48,52,56,60,64,68,72,76,80,84,88,92,96,100,100,100,100,100,100,100,100,100]],['扩张',[12,20,28,36,44,52,60,68,76,84,92,100,110,120,130,140,150,160,170,180,190,200,210,220,230,240,240,240,240,240,240,240]]];
const inputs=[
['reward','每场已确认奖励',10000,'RM；旧商业算例，非客户订单'],['fee','奖励外加服务费率',.15,'旧商业算例，非已批准定价'],['cpm','每千次合格播放奖励',5,'RM；旧商业算例'],['review','审核与支持／场',300,'RM；估计，非报价'],['data','计量与数据／场',100,'RM；估计，非报价'],['payment','支付／场',150,'RM；估计，非报价'],['exceptions','异常损失／场',50,'RM；估计，非报价'],['commission','活动获取／转介佣金／场',150,'RM；新增假设，每单发生；不属于品牌CAC'],['fulfillFixed','固定履约／月',2000,'RM；计入销售成本，也是固定17000的一部分'],['otherFixed','固定非履约运营／月',15000,'RM；不再另扣2000；原12000+5000重分类'],['dev','历史开发预算锚点',189750,'RM；已含开发预备金，非新范围报价'],['incremental','新增计量与反作弊开发',0,'未报价！零仅占位，资金需求是情景下限'],['prelaunch','建设期运营／月',12000,'RM；历史预算假设'],['launch','一次性启动池',50000,'RM；M5首批品牌获客、试点及专业服务；不重复计CAC'],['cac','独立销售品牌获客费',1500,'RM／新增品牌；M6起；不含每单佣金及固定销售工资'],['frequency','每活跃品牌每月活动',2,'说明假设；当月新品牌也完成全部活动'],['churn','月品牌流失率',.05,'说明假设；连续近似品牌数，不作人数承诺'],['initialCash','期初可用公司现金',0,'RM；创始人投入未知；只影响余额，不影响回本'],['example','单位经济示例活动／月',20,'说明情景；未含新增品牌CAC'],['buildMonths','建设月数',4,'M1–M4等额付开发费；非已签付款安排']];
const A=Object.fromEntries(inputs.map((x,i)=>[x[0],`'假设'!$D$${i+6}`]));
const get=k=>inputs.find(x=>x[0]===k)[2];
const independent=cases.map(([name,path])=>{let cum=0,min=0,prev=0,payback=null,positive=null; const months=[]; for(let m=1;m<=36;m++){const q=m<=4?0:path[m-5],brands=q/2,retained=Math.min(brands,prev*.95),newBrands=Math.max(0,brands-retained),cac=m<=5?0:newBrands*1500,revenue=q*1500,cogs=q*600+(m>4?2000:0),gp=revenue-cogs,contribution=q*750,op=m>4?contribution-17000-cac:-12000,dev=m<=4?189750/4:0,launch=m===5?50000:0,cf=op-dev-launch;cum+=cf;min=Math.min(min,cum);if(m>4&&op>=0&&positive===null)positive=m;if(m>4&&cum>=0&&payback===null)payback=m;months.push({month:m,campaigns:q,activeBrands:brands,newBrands,cac,revenue,cogs,grossProfit:gp,contribution,operatingResult:op,development:dev,launch,cashFlow:cf,cumulative: cum,eligibleViews:q*2000000});prev=brands;}return {name,paybackMonth:payback,payback:payback===null?'36个月内未回本':`第${payback}个月`,firstPositiveOperatingMonth:positive,peakCashNeed:-min,cumulative36:cum,revenue36:months.reduce((s,m)=>s+m.revenue,0),cac36:months.reduce((s,m)=>s+m.cac,0),months};});
await fs.writeFile(root+'assumptions.json',JSON.stringify({asOf:'2026-09-10',status:'创始人授权情景草稿；非预测或完整报价',inputs:inputs.map(([id,label,value,note])=>({id,label,value,note})),cases:cases.map(([name,campaigns])=>({name,monthlyCampaigns:[0,0,0,0,...campaigns]})),costPolicy:'每场佣金150独立；M5首批品牌获客归启动池50000；M6起新增与流失补充品牌×1500进入主现金流；保留品牌按95%连续近似；无重复计费',sources:['../../foundation/business-model-v2.md','../../foundation/belcort-handoff-v1.md']},null,2));
await fs.writeFile(root+'results.json',JSON.stringify({currency:'MYR',basis:'税前、融资前、未计营运资金时间差；不是税后净利',unit:{revenue:1500,brandSpend:11500,serviceFee:.15,brandSpendShare:1500/11500,variableFulfillment:600,campaignCommission:150,contribution:750,contributionMargin:.5,at20:{revenue:30000,cogs:14000,grossProfit:16000,grossMargin:16000/30000,operatingBeforeNewBrandCAC:-2000,operatingMargin:-2000/30000},breakevenBeforeNewBrandCAC:23,cacPaybackMonths:1},scenarios:independent},null,2));
await fs.writeFile(root+'handoff-early.md',independent.map(x=>`${x.name}：${x.payback}；首次单月经营不亏M${x.firstPositiveOperatingMonth??'无'}；峰值资金缺口RM${x.peakCashNeed.toFixed(0)}；M36累计RM${x.cumulative36.toFixed(0)}`).join('\n')+'\n成本决定：每场150佣金+M6起独立品牌CAC1500均计入主现金流；M5首批品牌由50000启动池覆盖。20场的-2000是新增CAC之前。所有活动路径为说明假设；新增开发0占位，未计税/利息/营运资金，非完整融资需求。\n');
const w=Workbook.create(), names=['总览','假设','单位经济','保守现金流','基准现金流','扩张现金流','品牌获客回收','敏感性'];
const sheets=Object.fromEntries(names.map(n=>[n,w.worksheets.add(n)]));
const fmt='#,##0;(#,##0);"—"';
function cell(s,p,v){const r=s.getRange(p);if(typeof v==='string'&&v.startsWith('=')){r.formulas=[[v]];r.format.font.color=v.includes('!')?'#16724A':'#172B3A';}else{r.values=[[v]];if(typeof v==='number'){r.format.font.color='#2458C5';r.format.fill='#FFF3CE';}}}
function init(s,title,end='K45'){s.showGridLines=false;s.getRange('A1:'+end).format.font={name:'Arial',size:11,color:'#172B3A'};s.getRange('A1:'+end).format.rowHeight=24;s.getRange('A1:B45').format.columnWidth=2;s.getRange('C1:C45').format.columnWidth=39;s.getRange('D1:AN45').format.columnWidth=17;s.getRange('D1:AN45').setNumberFormat(fmt);cell(s,'C2',title);s.getRange('C2').format.font.size=17;s.freezePanes.freezeRows(5);s.freezePanes.freezeColumns(3);}
function header(s,row,labels,start=3){s.getRangeByIndexes(row-1,start-1,1,labels.length).values=[labels];s.getRangeByIndexes(row-1,start-1,1,labels.length).format={fill:'#173D2A',font:{color:'#FFFFFF',bold:true},rowHeight:29};}
function note(s,row,text){cell(s,`C${row}`,text);s.getRange(`C${row}`).format.font.color='#8A4D10';}
for(const [n,s] of Object.entries(sheets))init(s,`Wringy｜${n}`,n.includes('现金流')?'AM44':'M65');
const a=sheets['假设'];header(a,5,['共同输入','数值','说明']);a.getRange('E5:E45').format.columnWidth=87;
inputs.forEach(([id,label,value,n],i)=>{cell(a,`C${i+6}`,label);cell(a,`D${i+6}`,value);cell(a,`E${i+6}`,n);});
for(const k of ['fee','churn'])a.getRange(A[k].split('!')[1].replaceAll('$','')).setNumberFormat('0.0%');
note(a,27,'蓝字浅黄＝可编辑输入；绿字＝跨表公式；月序为相对月份，无虚构开工日。');
note(a,28,'三情景并列计算，按要求各保留36个月明细；修改此处即自动更新相应情景。');
for(let m=1;m<=36;m++)cell(a,`${col(m+3)}30`,m);
cases.forEach(([n,p],i)=>{cell(a,`C${31+i}`,n+'｜活动数（说明输入）');for(let m=1;m<=36;m++)cell(a,`${col(m+3)}${31+i}`,m<=4?0:p[m-5]);});
note(a,36,'来源：phase-0/foundation/business-model-v2.md；belcort-handoff-v1.md（2026-09-10）');
note(a,37,'新增150佣金、600拆分、固定费用重分类及CAC路径：本轮授权情景假设，均非供应商报价。');
note(a,39,'会计口径：暂按代理规划假设，奖励代转款不计平台收入与成本；实际总额／净额待合同判断。');
cell(a,'C40','https://www.ifrs.org/news-and-events/updates/ifric/2022/ifric-update-april-2022/');
cell(a,'C41','https://openstax.org/books/principles-managerial-accounting/pages/3-1-explain-contribution-margin-and-calculate-contribution-margin-per-unit-contribution-margin-ratio-and-total-contribution-margin');
note(a,43,'不主张托管或支付许可已具备。费用均未报价；税、利息、收付款账期及折旧政策未建模。');
function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
const u=sheets['单位经济'];header(u,5,['每场经济与20场示例','数值']);
const unit=[['服务收入',`=${A.reward}*${A.fee}`],['品牌总支出',`=${A.reward}+D6`],['服务费率',`=${A.fee}`],['服务收入／品牌支出','=D6/D7'],['所需合格播放／场',`=${A.reward}/${A.cpm}*1000`],['可变履约成本／场',`=SUM(${A.review}:${A.exceptions})`],['活动获取佣金／场',`=${A.commission}`],['贡献／场','=D6-D11-D12'],['贡献率','=D13/D6'],['月活动量',`=${A.example}`],['月收入','=D6*D15'],['月销售成本（含固定履约）',`=D11*D15+${A.fulfillFixed}`],['毛利','=D16-D17'],['毛利率','=D18/D16'],['月贡献','=D13*D15'],['全部固定支出',`=${A.fulfillFixed}+${A.otherFixed}`],['经营结果（新增品牌CAC前）','=D20-D21'],['经营利润率（CAC前）','=D22/D16'],['盈亏平衡活动数（CAC前）','=IF(D13<=0,"无法达成",ROUNDUP(D21/D13,0))'],['税后净利润','未知：税、利息、折旧政策未齐']];
unit.forEach(([l,v],i)=>{cell(u,`C${i+6}`,l);cell(u,`D${i+6}`,v);});for(const r of [8,9,14,19,23])u.getRange(`D${r}`).setNumberFormat('0.0%');
note(u,28,'毛利扣可变及固定履约；贡献扣全部每场可变成本；固定2000不重复扣除。');note(u,29,'20场：经营亏损RM2,000，尚未扣新增品牌CAC；净利润未知。');note(u,30,'15%服务费 ≠ 13.04%品牌支出占比 ≠ 53.33%毛利率（20场）。');
const labels={6:'活动数',7:'活跃付费品牌（近似）',8:'留存品牌',9:'新增／替补品牌',10:'独立品牌CAC现金支出',11:'合格播放需求',12:'创作者奖励代转（非收入）',13:'品牌总支出（未税）',14:'平台服务收入',15:'可变履约成本',16:'固定履约成本',17:'销售成本合计',18:'毛利',19:'毛利率',20:'活动获取佣金',21:'贡献（CAC前）',22:'固定非履约支出',23:'建设期运营支出',24:'经营结果（含品牌CAC）',25:'经营利润率',26:'开发现金支付',27:'一次性启动现金支出',28:'融资前税前现金流',29:'累计公司现金流',30:'含期初现金的余额',31:'累计回本月标记',32:'单月经营不亏标记'};
cases.forEach(([n],i)=>{const s=sheets[n+'现金流'];cell(s,'C3',n+'｜全部为说明情景；RM，M1–M36');for(const [r,l]of Object.entries(labels))cell(s,`C${r}`,l);for(let m=1;m<=36;m++){let c=col(m+3),p=col(m+2),q=`${c}6`,r=x=>`${c}${x}`;cell(s,r(5),m);const f={6:`='假设'!${c}${31+i}`,7:`=${q}/${A.frequency}`,8:m===1?'=0':`=MIN(${r(7)},${p}7*(1-${A.churn}))`,9:`=MAX(0,${r(7)}-${r(8)})`,10:`=IF(${c}$5<=${A.buildMonths}+1,0,${r(9)}*${A.cac})`,11:`=${q}*'单位经济'!$D$10`,12:`=${q}*${A.reward}`,13:`=${r(12)}+${r(14)}`,14:`=${q}*'单位经济'!$D$6`,15:`=${q}*'单位经济'!$D$11`,16:`=IF(${c}$5>${A.buildMonths},${A.fulfillFixed},0)`,17:`=SUM(${r(15)}:${r(16)})`,18:`=${r(14)}-${r(17)}`,19:`=IF(${r(14)}=0,"不适用",${r(18)}/${r(14)})`,20:`=${q}*${A.commission}`,21:`=${r(14)}-${r(15)}-${r(20)}`,22:`=IF(${c}$5>${A.buildMonths},${A.otherFixed},0)`,23:`=IF(${c}$5<=${A.buildMonths},${A.prelaunch},0)`,24:`=${r(18)}-${r(20)}-${r(22)}-${r(23)}-${r(10)}`,25:`=IF(${r(14)}=0,"不适用",${r(24)}/${r(14)})`,26:`=IF(${c}$5<=${A.buildMonths},(${A.dev}+${A.incremental})/${A.buildMonths},0)`,27:`=IF(${c}$5=${A.buildMonths}+1,${A.launch},0)`,28:`=${r(24)}-${r(26)}-${r(27)}`,29:m===1?`=${r(28)}`:`=${p}29+${r(28)}`,30:`=${A.initialCash}+${r(29)}`,31:`=IF(AND(${c}$5>${A.buildMonths},${r(29)}>=0),${c}$5,999)`,32:`=IF(AND(${c}$5>${A.buildMonths},${r(24)}>=0),${c}$5,999)`};for(const [rr,v]of Object.entries(f))cell(s,r(rr),v);}
s.getRange('D5:AM5').format.fill='#173D2A';s.getRange('D5:AM5').format.font.color='#FFFFFF';for(const r of [19,25])s.getRange(`D${r}:AM${r}`).setNumberFormat('0.0%');s.getRange('D7:AM9').setNumberFormat('0.00');for(const r of [14,18,21,24,28,29])s.getRange(`C${r}:AM${r}`).format.fill='#E9F0F2';note(s,35,'M5首批获客已计入启动池；M6起新增/替补品牌另付CAC。当月获得品牌当月即完成全部活动。');note(s,36,'现金流不含融资，不含税、利息及营运资金账期；开发全部按现金支出。经营结果为折旧摊销前代理指标。');note(s,37,'固定费用不随规模增长仅为情景假设；扩张需另验容量、招聘、数据吞吐及报价。');});
const cac=sheets['品牌获客回收'];header(cac,5,['独立品牌获客经济','数值']);[['独立品牌CAC',`=${A.cac}`],['每月活动／品牌',`=${A.frequency}`],['每场贡献（已扣150佣金）',"='单位经济'!D13"],['每品牌月贡献','=D7*D8'],['简单CAC回收（月）','=IF(D9<=0,"无法回收",D6/D9)']].forEach(([l,v],i)=>{cell(cac,`C${i+6}`,l);cell(cac,`D${i+6}`,v);});note(cac,12,'RM1,500独立获客费 ÷ RM1,500月贡献 = 1个月；不能替代公司累计回本。');note(cac,13,'下表为1个新品牌的留存期望贡献；第1月完整贡献，第2月起按留存衰减。');header(cac,15,['品牌年龄（月）','预期留存品牌','月贡献','累计贡献','扣CAC后累计']);for(let t=1;t<=36;t++){let r=t+15;cell(cac,`C${r}`,t);cell(cac,`D${r}`,`=(1-${A.churn})^(C${r}-1)`);cell(cac,`E${r}`,`=D${r}*$D$9`);cell(cac,`F${r}`,t===1?`=E${r}`:`=F${r-1}+E${r}`);cell(cac,`G${r}`,`=F${r}-$D$6`);}cac.getRange('D16:D51').setNumberFormat('0.0%');note(cac,54,'这是贡献口径回收，不分摊固定支出；无销售前置周期、退款或复购延迟假设。');
const sen=sheets['敏感性'];note(sen,3,'公式即时计算｜每月经营结果：未含新增品牌CAC；其影响见下方独立敏感性。');header(sen,5,['活动数／服务费率',.10,.125,.15,.175,.20]);sen.getRange('D5:H5').setNumberFormat('0.0%');[10,20,23,40,80,160].forEach((q,i)=>{const r=i+6;cell(sen,`C${r}`,q);for(let j=4;j<=8;j++)cell(sen,`${col(j)}${r}`,`=$C${r}*(${A.reward}*${col(j)}$5-'单位经济'!$D$11-${A.commission})-'单位经济'!$D$21`);});header(sen,15,['履约成本／费率',.10,.125,.15,.175,.20]);sen.getRange('D15:H15').setNumberFormat('0.0%');[400,600,800,1000,1500].forEach((cost,i)=>{const r=i+16;cell(sen,`C${r}`,cost);for(let j=4;j<=8;j++)cell(sen,`${col(j)}${r}`,`=IF(${A.reward}*${col(j)}$15-$C${r}-${A.commission}<=0,"无法达成",ROUNDUP('单位经济'!$D$21/(${A.reward}*${col(j)}$15-$C${r}-${A.commission}),0))`);});note(sen,22,'上表：覆盖固定费用所需活动数（新增品牌CAC之前），向上取整。');header(sen,25,['新增品牌数／CAC',750,1500,2250,3000]);[0,2,5,10,20].forEach((x,i)=>{let r=i+26;cell(sen,`C${r}`,x);for(let j=4;j<=7;j++)cell(sen,`${col(j)}${r}`,`='单位经济'!$D$22-$C${r}*${col(j)}$25`);});note(sen,32,'上表：按单位经济示例活动量，扣独立品牌CAC后的月经营结果。');
const sum=sheets['总览'];sum.getRange('D1:F65').format.columnWidth=25;note(sum,3,'情景草稿｜MYR｜新计量与反作弊开发未报价：零占位，非完整资金估计');header(sum,5,['核心结果','保守','基准','扩张']);const sl={6:'公司累计回本（月序）',7:'首次单月经营不亏（月序）',8:'最大累计资金缺口／RM',9:'36个月累计现金流／RM',10:'36个月服务收入／RM',11:'M36每月活动数',12:'M36合格播放需求',13:'36个月新增品牌CAC／RM'};for(const[r,l]of Object.entries(sl))cell(sum,`C${r}`,l);cases.forEach(([n],i)=>{let c=col(i+4),s=`'${n}现金流'`;const f={6:`=IF(MIN(${s}!D31:AM31)=999,"36个月内未回本",MIN(${s}!D31:AM31))`,7:`=IF(MIN(${s}!D32:AM32)=999,"36个月内未转正",MIN(${s}!D32:AM32))`,8:`=MAX(0,-MIN(${s}!D29:AM29))`,9:`=${s}!AM29`,10:`=SUM(${s}!D14:AM14)`,11:`=${s}!AM6`,12:`=${s}!AM11`,13:`=SUM(${s}!D10:AM10)`};for(const[r,v]of Object.entries(f))cell(sum,`${c}${r}`,v);});
header(sum,16,['20场／月：费率与利润不同','数值']);[['服务费率',"='单位经济'!D8"],['平台收入／品牌支出',"='单位经济'!D9"],['毛利率（含固定履约）',"='单位经济'!D19"],['贡献率（含每场佣金）',"='单位经济'!D14"],['经营结果（新增CAC前）',"='单位经济'!D22"],['盈亏平衡场数（新增CAC前）',"='单位经济'!D24"],['品牌CAC简单回收（月）',"='品牌获客回收'!D10"]].forEach(([l,v],i)=>{cell(sum,`C${i+17}`,l);cell(sum,`D${i+17}`,v);});sum.getRange('D17:D20').setNumberFormat('0.0%');note(sum,25,'公司回本包含开发、运营、启动及独立品牌CAC；融资现金不算回本收入。');note(sum,26,'单月经营结果是折旧摊销前规划指标；税后净利润未知。');
header(sum,43,['月序','保守累计现金','基准累计现金','扩张累计现金']);for(let m=1;m<=36;m++){cell(sum,`C${m+43}`,`M${m}`);cases.forEach(([n],i)=>cell(sum,`${col(i+4)}${m+43}`,`='${n}现金流'!${col(m+3)}29`));}const chart=sum.charts.add('line',sum.getRange('C43:F79'));chart.title='公司累计现金流（RM，融资前税前）';chart.setPosition('H5','Q24');chart.yAxis={numberFormatCode:'#,##0',numberFormatSourceLinked:false};chart.xAxis={axisType:'textAxis'};['#5C6258','#173D2A','#171A14'].forEach((c,i)=>chart.series.items[i].line={fill:c,style:'solid',width:2});
// All reviewed submissions drive platform review cost; rejected/flagged/appealed work is included.
header(a,45,['审核、支付与收款驱动','数值','说明']);
const extra=[['全量审核提交／场',200,'包括通过与拒绝的所有提交；不是仅已付款提交'],['平台平均审核分钟／提交',1.5,'含异常及申诉的加权平均；假设，非效率基准；不含品牌自己审核'],['平台审核时薪',60,'RM／小时；假设，非报价'],['支付费模式',0,'0＝原150占位；1＝全品牌资金×费率＋每场固定费'],['全品牌资金支付费率',.03,'3%仅敏感性假设，非Whop或市场报价'],['额外每场支付固定费',0,'RM；出款与固定费待报价，零仅占位'],['服务费收款延迟（月）',0,'0或1；基准同月收款是假设；非外部平台账期']];
extra.forEach(([l,v,n],i)=>{cell(a,`C${46+i}`,l);cell(a,`D${46+i}`,v);cell(a,`E${46+i}`,n);});a.getRange('D50').setNumberFormat('0.0%');
cell(a,'D9','=D46*D47/60*D48');cell(a,'E9','全量提交×含申诉平均分钟÷60×时薪；不得再重复加申诉成本');
cell(a,'C53','原支付占位／场');cell(a,'D53',150);cell(a,'E53','可编辑；非市场报价；模式0采用');cell(a,'D11',"=IF(D49=0,D53,D6*(1+D7)*D50+D51)");cell(a,'E11','150为历史估计占位；模式1按全品牌资金计费，非仅服务费');
a.getRange('D49').dataValidation={rule:{type:'whole',operator:'between',formula1:0,formula2:1}};
a.getRange('D52').dataValidation={rule:{type:'whole',operator:'between',formula1:0,formula2:1}};
cases.forEach(([n])=>{const s=sheets[n+'现金流'];cell(s,'C33','当月服务费现金收款');cell(s,'C34','期末服务费应收款');for(let m=1;m<=36;m++){const c=col(m+3),p=col(m+2);cell(s,`${c}33`,m===1?`=IF('假设'!$D$52=0,${c}14,0)`:`=IF('假设'!$D$52=0,${c}14,${p}14)`);cell(s,`${c}34`,m===1?`=${c}14-${c}33`:`=${p}34+${c}14-${c}33`);cell(s,`${c}28`,`=${c}24-${c}26-${c}27-${c}14+${c}33`);}cell(s,'C36','现金流已含0/1月服务费收款延迟；未计税、利息及其余营运资金；不作税后净利。');});
header(sen,35,['全资金支付费率','每场支付成本','每场贡献','20场毛利率','20场经营（CAC前）']);
[0,.02,.03,.04].forEach((rate,i)=>{const r=i+36;cell(sen,`C${r}`,rate);cell(sen,`D${r}`,`='单位经济'!$D$7*C${r}+'假设'!$D$51`);cell(sen,`E${r}`,`='单位经济'!$D$13+'假设'!$D$11-D${r}`);cell(sen,`F${r}`,`=('单位经济'!$D$18+('假设'!$D$11-D${r})*'假设'!$D$24)/'单位经济'!$D$16`);cell(sen,`G${r}`,`='单位经济'!$D$22+('假设'!$D$11-D${r})*'假设'!$D$24`);});sen.getRange('C36:C39').setNumberFormat('0.0%');sen.getRange('F36:F39').setNumberFormat('0.0%');note(sen,41,'3%×RM11,500＝RM345；未加待报价出款固定费。改假设D49为1可重算所有公司回本。');
cell(cac,'C10','简单回收期（月；持续采购）');cell(cac,'C12','单品牌持续每月2场、不流失的简单回收期；非观察到的客户群回收期。');
note(u,32,'毛利率以平台净服务费收入为分母；代理／主要责任人及实际收入确认仍待合同判断。');
cases.forEach(([n])=>{const s=sheets[n+'现金流'];cell(s,'C39','支付费敏感性：全品牌资金费率');cell(s,'C40','敏感性现金流（同收款账期）');cell(s,'C41','敏感性累计现金流');cell(s,'C42','敏感性回本月标记');for(let m=1;m<=36;m++){const c=col(m+3),p=col(m+2);cell(s,`${c}39`,"='假设'!$D$50");cell(s,`${c}40`,`=${c}28-('单位经济'!$D$7*${c}39+'假设'!$D$51-'假设'!$D$11)*${c}6`);cell(s,`${c}41`,m===1?`=${c}40`:`=${p}41+${c}40`);cell(s,`${c}42`,`=IF(AND(${c}$5>'假设'!$D$25,${c}41>=0),${c}$5,999)`);}s.getRange('D39:AM39').setNumberFormat('0.0%');});
header(sen,44,['全品牌资金费率情景','保守','基准','扩张']);cell(sen,'C45','公司累计回本（月序）');cell(sen,'C46','峰值资金缺口／RM');cell(sen,'C47','36个月累计现金流／RM');cases.forEach(([n],i)=>{const c=col(i+4),s=`'${n}现金流'`;cell(sen,`${c}45`,`=IF(MIN(${s}!D42:AM42)=999,"36个月内未回本",MIN(${s}!D42:AM42))`);cell(sen,`${c}46`,`=MAX(0,-MIN(${s}!D41:AM41))`);cell(sen,`${c}47`,`=${s}!AM41`);});note(sen,49,'此表使用假设中的全资金费率（默认3%），同其他成本及收款账期实时计算。');
sum.getRange('D6:F13').format.font.color='#172B3A';sum.getRange('D17:D23').format.font.color='#172B3A';
for(const n of ['总览','单位经济','敏感性'])sheets[n].tabColor='#173D2A';a.tabColor='#B18A32';
w.recalculate();
const verification=[];for(let i=0;i<3;i++){const actual=sheets[cases[i][0]+'现金流'].getRange('AM29').values[0][0];if(Math.abs(actual-independent[i].cumulative36)>1e-6)throw new Error('Independent mismatch '+actual);verification.push({case:cases[i][0],cumulative36:actual,independent:independent[i].cumulative36});}
// Verify input change propagation, then restore before final export.
cell(a,'D7',.16);w.recalculate();if(Math.abs(u.getRange('D6').values[0][0]-1600)>1e-6)throw Error('fee recalculation');cell(a,'D7',.15);cell(a,'D17',10000);w.recalculate();for(let i=0;i<3;i++){if(Math.abs(sheets[cases[i][0]+'现金流'].getRange('AM29').values[0][0]-(independent[i].cumulative36-10000))>1e-6)throw Error('dev recalculation');}cell(a,'D17',0);w.recalculate();
await fs.writeFile(root+'verification.json',JSON.stringify({engine:'@oai/artifact-tool',independentChecks:verification,inputTests:['fee15→16→15: revenue1500→1600→1500','incremental dev0→10000→0: each cumulative36 declines10000 then restores'],nativeExcel:'未在桌面Excel运行；已验证库重算与导出缓存'},null,2));
const scenarioSnapshot=()=>cases.map(([name])=>{const s=sheets[name+'现金流'],cum=s.getRange('D29:AM29').values[0],marks=s.getRange('D31:AM31').values[0];return{name,paybackMonth:Math.min(...marks)===999?null:Math.min(...marks),peakCashNeed:-Math.min(0,...cum),cumulative36:cum[35]};});
cell(a,'D49',1);w.recalculate();const payment3Percent=scenarioSnapshot();if(Math.abs(u.getRange('D11').values[0][0]-795)>1e-6)throw Error('full funding payment test');cell(a,'D49',0);cell(a,'D52',1);w.recalculate();const collectionLag1Month=scenarioSnapshot();for(let i=0;i<3;i++){if(Math.abs(collectionLag1Month[i].cumulative36-independent[i].cumulative36+independent[i].months[35].revenue)>1e-6)throw Error('collection lag reconciliation');}cell(a,'D52',0);w.recalculate();
const aj=JSON.parse(await fs.readFile(root+'assumptions.json'));aj.additionalInputs=extra.map(([label,value,note],i)=>({label,value,note,cell:`假设!D${46+i}`}));aj.formulaDrivers={review:'total reviewed submissions × average minutes including flags and appeals / 60 × hourly rate',payment:'mode0 = RM150 placeholder; mode1 = full brand funding × rate + fixed fees',collection:'0 or 1 month; same-month cost payments; creator pass-through excluded under agent planning assumption'};await fs.writeFile(root+'assumptions.json',JSON.stringify(aj,null,2));const result=JSON.parse(await fs.readFile(root+'results.json'));result.sensitivities={payment3Percent,collectionLag1Month};await fs.writeFile(root+'results.json',JSON.stringify(result,null,2));
const scan=await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:30}});await fs.writeFile(root+'formula-scan.ndjson',scan.ndjson);console.log(scan.ndjson);
for(const n of names){let range=n.includes('现金流')?'C2:J34':n==='假设'?'C2:F25':n==='品牌获客回收'?'C2:G22':n==='总览'?'C2:Q26':n==='敏感性'?'C2:H41':'C2:H30';const png=await w.render({sheetName:n,range,scale:1.4,format:'png'});await fs.writeFile(out+n+'.png',new Uint8Array(await png.arrayBuffer()));}
const senPng=await w.render({sheetName:'敏感性',range:'C35:H49',scale:1.4,format:'png'});await fs.writeFile(out+'支付费公司回本.png',new Uint8Array(await senPng.arrayBuffer()));
const extraPng=await w.render({sheetName:'假设',range:'C45:F53',scale:1.4,format:'png'});await fs.writeFile(out+'审核与账期输入.png',new Uint8Array(await extraPng.arrayBuffer()));
await (await SpreadsheetFile.exportXlsx(w)).save(out+'Wringy-36个月财务模型.xlsx');
console.log(JSON.stringify(independent.map(({months,...rest})=>rest),null,2));
