from shared import source_css,canonical_css,samples
import pathlib,json,base64
P=pathlib.Path(__file__).parent
T=json.loads((P/'tokens.json').read_text()); S=T['samples']
def pic(n):return 'data:image/png;base64,'+base64.b64encode((P/'assets'/n).read_bytes()).decode()
css=source_css()+'''
*{box-sizing:border-box}body{margin:0;color:var(--ink);background:var(--surface);font-family:var(--font-sans);font-size:18px;line-height:1.6}h1,h2,h3,p{margin:0}h1{font-size:44px;line-height:1.3;letter-spacing:-1.5px}h2{font-size:28px;line-height:1.4}h3{font-size:20px}small,.muted{color:var(--secondary)}small{font-size:14px}.product{width:1440px;background:white;min-height:900px;margin:32px auto;overflow:hidden}.top{height:80px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 40px}.wordmark{font-weight:700;font-size:30px;letter-spacing:-1.5px}.app{display:grid;grid-template-columns:200px 1fr;min-height:820px}.nav{border-right:1px solid var(--line);padding:32px 20px;font-size:16px}.nav div{padding:12px 16px;margin:4px 0}.selected{background:var(--surface);border-radius:6px;font-weight:600}.main{padding:42px 48px}.eyebrow{font-size:13px;letter-spacing:2px;text-transform:uppercase;margin-bottom:16px;color:var(--secondary)}.split{display:grid;grid-template-columns:1.25fr 1fr;gap:40px;margin-top:32px}.photo{width:100%;height:360px;object-fit:cover;border-radius:10px}.btn{display:inline-block;padding:12px 22px;border-radius:6px;background:var(--citron);color:var(--ink);font-size:16px;font-weight:600;border:1px solid transparent}.neutral{background:var(--surface);border-color:var(--line)}.row{padding:18px 0;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:20px}.tag{font-size:14px;padding:4px 10px;background:var(--surface);border:1px solid var(--line);border-radius:5px;white-space:nowrap}.notice{padding:16px 20px;background:var(--surface);margin-top:24px;border-left:3px solid var(--forest);font-size:16px}.detail{display:grid;grid-template-columns:1fr 260px;gap:40px;margin-top:30px}.props{border-left:1px solid var(--line);padding-left:24px;font-size:15px}.props p{margin:18px 0}.steps{max-width:800px;margin:36px auto}.step{display:grid;grid-template-columns:48px 1fr;gap:24px;padding:20px 0}.num{border:1px solid var(--line);width:40px;height:40px;border-radius:50%;display:grid;place-items:center}.done{background:var(--forest);color:white}.step p{color:var(--secondary);font-size:16px;margin-top:5px}.foot{font-size:13px;color:var(--secondary);margin-top:28px}.titleline{display:flex;justify-content:space-between;gap:24px;align-items:center}button{font:inherit;cursor:pointer}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid var(--focus);outline-offset:3px}
'''
css=canonical_css(css)
def top(label):return '<header class="top"><span class="wordmark">Wringy</span><span>'+label+'</span><small>演示工作区 · 无真实数据</small></header>'
def nav(active):return '<aside class="nav"><small>品牌工作区</small>'+''.join('<div class="'+('selected' if n==active else '')+'">'+n+'</div>' for n in ['活动概览','作品审核','创作者','工作区设置'])+'</aside>'
photo=pic('creator-studio.png'); bottle=pic('bottle-craft-detail.png')
a='''<section class="product" id="product-overview">'''+top('活动 / 概览')+'<div class="app">'+nav('活动概览')+'''<main class="main"><div class="eyebrow">Activity brief / 示例活动</div><div class="titleline"><h1>日常好物演示</h1><span class="btn">查看参与要求 →</span></div><p class="muted" style="margin-top:12px">用真实使用场景，讲清一件日常好物。</p><div class="split"><div><img class="photo" src="'''+photo+'''"><small>概念场景，非真实客户</small><div class="notice">本页为活动说明示例。参与及奖励规则仍待业务确认。</div></div><div><h2>拍什么 · 怎样交付</h2><div class="row"><span>产品</span><b>无品牌随行水瓶</b></div><div class="row"><span>内容形式</span><b>一条日常使用演示</b></div><div class="row"><span>画面要求</span><b>主体清晰 · 使用过程完整</b></div><div class="row"><span>提交材料</span><b>预览作品与内容说明</b></div><h3 style="margin-top:28px">发布前先确认</h3><p class="muted" style="margin-top:10px;font-size:16px">审核通过后再进入发布步骤。最终审核、奖励资格和实际付款分别记录。</p></div></div><p class="foot">Wringy 独立产品设计草案 / 示例内容，不代表已上线功能</p></main></div></section>'''
b='''<section class="product" id="review-detail">'''+top('作品审核 / 作品 001')+'<div class="app">'+nav('作品审核')+'''<main class="main"><div class="eyebrow">Work review / 作品详情</div><h1 style="font-size:32px;letter-spacing:-.5px">水瓶日常使用演示</h1><p class="muted" style="margin-top:12px">日常好物演示 · 示例创作者 A · 作品 001</p><div class="detail"><article><img class="photo" style="height:320px" src="'''+bottle+'''"><small>概念场景，非真实客户 · 静态作品预览</small><div class="row"><h3>审核记录</h3><span class="tag">发布前审核通过</span></div><p style="margin-top:18px;font-size:17px">画面已包含水瓶主体和使用细节。下一步：由创作者提交发布链接，再进行最终审核。</p><div class="notice">这是一条审核记录，不是付款凭证。</div></article><aside class="props"><h3>作品属性</h3><p><small>所属活动</small><br>日常好物演示</p><p><small>发布前审核</small><br>通过</p><p><small>最终审核</small><br>尚未开始</p><p><small>奖励资格</small><br>尚未确认</p><p><small>银行实际付款</small><br>尚未付款</p><span class="btn neutral">查看提交材料</span></aside></div></main></div></section>'''
c='''<section class="product" id="creator-progress">'''+top('创作者 / 我的进度')+'''<main class="steps"><div class="eyebrow">Your next step / 创作者视图</div><h1>知道进展，也知道下一步。</h1><p class="muted" style="margin-top:12px">日常好物演示 · 无品牌随行水瓶</p>'''+''.join('<div class="step"><span class="num '+('done' if i<3 else '')+'">'+str(i)+'</span><div><h3>'+h+'</h3><p>'+p+'</p></div></div>' for i,h,p in [(1,'提交预览作品','已完成 · 作品 001 已收到'),(2,'发布前审核通过','已完成 · 可以进入发布步骤'),(3,'提交发布链接','当前步骤 · 发布后提交对应链接'),(4,'最终审核与奖励资格','待处理 · 最终审核通过不等于已付款'),(5,'查看银行实际付款记录','尚未付款 · 以实际付款记录为准')])+'''<div style="margin:16px 0 0 72px"><span class="btn">提交发布链接 →</span><p class="foot">产品流程提案，业务规则待批准。无真实创作者或交易数据。</p></div></main></section>'''
(P/'product-exports.html').write_text(samples('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>Wringy 产品示例</title><style>'+css+'</style><body>'+a+b+c+'</body></html>'))
(P/'product-fragments.json').write_text(json.dumps({'css':css,'overview':a,'detail':b,'progress':c},ensure_ascii=False))
print('product export HTML ready')
