import json,pathlib
p=pathlib.Path(__file__).parent;t=json.loads((p/'tokens.json').read_text())
t['provenance']={'classification':'Wringy independent proposal','reference_capture_membership':'unverified','reference_values_extracted':False,'approval':'User authorized draft; not approved production design system','date':'2026-09-10'}
t['typography']={'display':{'size':56,'lineHeight':1.2,'weight':600},'brandHeading':{'size':40,'lineHeight':1.3,'weight':600},'objectHeading':{'size':32,'lineHeight':1.4,'weight':600},'sectionHeading':{'size':24,'lineHeight':1.4,'weight':600},'body':{'size':18,'lineHeight':1.65,'weight':400},'app':{'size':15,'lineHeight':1.5,'weight':400},'caption':{'size':13,'lineHeight':1.5,'weight':400},'mobileHeading':{'size':30,'lineHeight':1.3,'weight':600},'deckLabel':{'size':32,'lineHeight':1.35,'weight':600}}
t['layout']={'brandMax':1280,'brandColumns':12,'gutter':24,'longReadMax':720,'settingsMax':420,'creatorMax':800,'sidebar':200,'properties':260,'compactRowMin':48,'controlMin':44,'mobileBreakpoint':480,'tabletBreakpoint':800,'productExportWidth':1440,'productExportHeight':900,'deckExportWidth':1000,'deckExportHeight':760}
t['motion']={'durationFastMs':120,'durationStandardMs':180,'easing':'ease-out','reducedMotion':'disable decorative movement; retain state change'}
t['semantic']={'action':{'background':'citron','foreground':'ink'},'selection':{'background':'surface','foreground':'ink'},'success':{'foreground':'success','background':'canvas','requiresText':True},'error':{'foreground':'error','background':'canvas','requiresText':True},'focus':{'color':'focus','width':3,'offset':3},'inputBorder':'secondary','decorativeDivider':'line','paid':'actual bank record + explicit text; never inferred from accent color'}
t['samples'].update({'workTitle':'水瓶日常使用演示','workspace':'示例品牌工作区','requirement':'主体清晰 · 使用过程完整','deliverable':'预览作品 ＋ 内容说明','queue':[{'id':'作品 001','state':'发布前通过','pending':False},{'id':'作品 002','state':'待审核','pending':True},{'id':'作品 003','state':'待审核','pending':True}],'counts':{'total':3,'pending':2,'prepublishapproved':1},'finalReview':'尚未开始','eligibility':'尚未确认'})
(p/'tokens.json').write_text(json.dumps(t,ensure_ascii=False,indent=2)+'\n')
