const fs=require('fs'),path=require('path');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),OUT=path.resolve(ROOT,'../output'),URL=process.env.BASE_URL||'http://127.0.0.1:8878';
const manifest=JSON.parse(fs.readFileSync(path.join(ROOT,'public/registry-manifest.json'))),checks=[],errors=[],shots=[];
let browser,page;
function assert(ok,msg){if(!ok)throw Error(msg)}
async function test(name,fn){try{const evidence=await fn();checks.push({name,passed:true,evidence:evidence??true});console.log('PASS',name)}catch(e){checks.push({name,passed:false,error:e.message});console.log('FAIL',name,e.message);await page.keyboard.press('Escape').catch(()=>{});}}
async function go(id){await page.evaluate(id=>{location.hash=id},id);await page.locator(`#specimen[data-component-id="${id}"]`).waitFor();await page.waitForTimeout(70)}
async function state(label){await page.locator('#state-select').click();await page.getByRole('option',{name:label,exact:true}).click()}
async function screenshot(name){const p=path.join(OUT,name+'.png');await page.screenshot({path:p});shots.push(name+'.png')}
(async()=>{fs.mkdirSync(OUT,{recursive:true});browser=await chromium.launch({...(process.env.PLAYWRIGHT_BROWSER==='chromium'?{}:{channel:'chrome'}),headless:true});page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));await page.goto(URL);await page.locator('#specimen').waitFor();await page.evaluate(()=>document.fonts.ready);
await test('64 entries / each renders its own real component or documented pattern',async()=>{const empty=[];for(const entry of manifest.entries){await go(entry.id);const count=await page.locator('#specimen').evaluate(el=>el.children.length);if(!count)empty.push(entry.id)}assert(!empty.length,'empty '+empty.join(','));assert(!errors.length,errors.join('\n'));return {native:61,patterns:3,rendered:64}});
await test('navigation / search and no-match recovery',async()=>{const search=page.getByRole('textbox',{name:'搜索组件'});await search.fill('checkbox');assert(await page.locator('[data-component="checkbox"]').count()===1,'checkbox missing');await search.fill('not-a-real-component');assert(await page.getByText('没有匹配组件',{exact:true}).isVisible(),'empty state missing');await page.getByRole('button',{name:'清除搜索',exact:true}).click();assert(await page.locator('[data-component]').count()===64,'full catalog not restored');});
await test('button / official variants disabled and real loading state',async()=>{await go('button');await state('禁用');assert(await page.locator('#button-demo').isDisabled(),'disabled missing');await state('处理中');assert(await page.locator('#button-demo [data-slot="spinner"]').count()===1,'official Spinner absent');assert(await page.locator('#button-demo').getAttribute('aria-busy')==='true','busy missing');await state('直接操作');await page.locator('#button-demo').click();await page.getByText('本地演示操作已触发',{exact:true}).waitFor();});
await test('checkbox / actual mixed checked disabled invalid semantics',async()=>{await go('checkbox');await state('不确定 / 部分');assert(await page.locator('#checkbox-demo').getAttribute('aria-checked')==='mixed','not mixed');await page.locator('#checkbox-demo').click();assert(await page.locator('#checkbox-demo').getAttribute('aria-checked')==='true','mixed click failed');await state('校验错误');assert(await page.locator('#checkbox-demo').getAttribute('aria-invalid')==='true','invalid absent');await state('禁用');assert(await page.locator('#checkbox-demo').isDisabled(),'not disabled');});
await test('input / readonly cannot change, invalid associates visible message',async()=>{await go('input');await state('只读');assert(await page.locator('#input-demo').getAttribute('readonly')!==null,'not readonly');await state('校验错误');assert(await page.locator('#input-demo').getAttribute('aria-invalid')==='true','invalid missing');assert(await page.getByText('请输入作品标题。',{exact:true}).isVisible(),'message absent');});
await test('field / required focus and invalid email, failure preserves input, retry succeeds',async()=>{await go('field');await page.locator('#form-submit').click();assert(await page.locator('#form-title').evaluate(el=>el===document.activeElement),'required focus');await page.locator('#form-title').fill('应保留的作品');await page.locator('#form-email').fill('invalid');await page.locator('#form-submit').click();assert(await page.locator('#form-email').evaluate(el=>el===document.activeElement),'email focus');await page.locator('#form-email').fill('creator@example.com');await page.locator('#form-note').fill('原始说明不能丢失');await page.locator('#form-submit').click();assert(await page.locator('#form-submit').isDisabled(),'busy not disabled');await page.getByRole('alert').filter({hasText:'保存失败，内容已保留'}).waitFor();assert(await page.locator('#form-title').inputValue()==='应保留的作品','title lost');await page.waitForTimeout(30);assert(await page.locator('#form-submit').evaluate(el=>el===document.activeElement),'focus not restored after async failure');assert(await page.locator('#form-note').inputValue()==='原始说明不能丢失','note lost');await page.locator('#form-submit').click();await page.getByText('说明已保存',{exact:true}).waitFor();});
await test('switch radio slider / state changes with actual keyboard',async()=>{await go('switch');await page.locator('#switch-demo').focus();await page.keyboard.press('Space');assert(await page.locator('#switch-demo').getAttribute('aria-checked')==='true','switch keyboard');await go('radio-group');await page.locator('#radio-all').focus();await page.keyboard.press('ArrowDown');assert(await page.locator('#radio-mine').getAttribute('aria-checked')==='true','radio keyboard');await go('slider');assert(await page.getByRole('group',{name:/预览缩放范围/}).count()===1,'range context missing');await page.getByRole('slider',{name:'Minimum',exact:true}).focus();await page.keyboard.press('ArrowRight');assert(await page.getByRole('slider',{name:'Minimum',exact:true}).getAttribute('aria-valuenow')==='30','slider keyboard');assert(await page.getByRole('slider',{name:'Maximum',exact:true}).getAttribute('aria-valuenow')==='80','upper thumb missing');});
await test('accordion / actual expanded content and disabled trigger',async()=>{await go('accordion');const trigger=page.getByRole('button',{name:'作品需要满足哪些要求？'});await trigger.focus();await page.keyboard.press('Enter');assert(await trigger.getAttribute('aria-expanded')==='true','expand failed');await state('禁用');assert(await page.getByRole('button',{name:'作品需要满足哪些要求？'}).isDisabled(),'disabled trigger');});
await test('dialog / initial focus, cycle Tab, Escape and return focus',async()=>{await go('dialog');const trigger=page.getByRole('button',{name:'打开对话框',exact:true});await trigger.click();const d=page.getByRole('dialog',{name:'编辑演示视图'});await d.waitFor();assert(await d.evaluate(el=>el.contains(document.activeElement)),'initial focus absent');const input=d.getByRole('textbox',{name:'演示视图名称'});await input.fill('');assert(await d.getByRole('button',{name:'应用到本页'}).isDisabled(),'invalid dialog permits submit');await input.fill('保留视图');for(let i=0;i<8;i++){await page.keyboard.press('Tab');assert(await d.evaluate(el=>el.contains(document.activeElement)),'focus escaped')}await page.keyboard.press('Escape');await d.waitFor({state:'hidden'});assert(await trigger.evaluate(el=>el===document.activeElement),'focus not restored');await trigger.click();assert(await page.getByRole('textbox',{name:'演示视图名称'}).inputValue()==='保留视图','draft lost');await page.keyboard.press('Escape');});
await test('select / keyboard open choice Escape and disabled option',async()=>{await go('select');const trigger=page.locator('#specimen [data-slot="select-trigger"]').last();await trigger.focus();await page.keyboard.press('Space');await page.getByRole('listbox').waitFor();assert(await page.getByRole('option',{name:'归档课程 · 不可选'}).getAttribute('data-disabled')!==null,'disabled option missing');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert(await trigger.innerText()!=='请选择课程','selection failed');await trigger.click();await page.keyboard.press('Escape');assert(await trigger.evaluate(el=>el===document.activeElement),'return focus absent');});
await test('tabs / actual roving focus and panel selection',async()=>{await go('tabs');const tabs=page.locator('#specimen [role="tab"]');const first=tabs.first();await first.focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelectorAll('#specimen [role="tab"]')[1]?.getAttribute('aria-selected')==='true');assert(await tabs.nth(1).getAttribute('aria-selected')==='true','arrow selection failed');await page.keyboard.press('Home');await page.waitForFunction(()=>document.querySelector('#specimen [role="tab"]')?.getAttribute('aria-selected')==='true');assert(await first.getAttribute('aria-selected')==='true','Home failed');});
await test('questionnaire / required gating and completion',async()=>{await go('questionnaire');await page.getByLabel('创作者',{exact:true}).check();await page.getByRole('button',{name:'下一步',exact:true}).click();await page.getByText('优先关注哪项内容？',{exact:true}).waitFor();await page.getByLabel('作品内容',{exact:true}).check();await page.getByRole('button',{name:'完成',exact:true}).click();await page.getByText('回答已记录在当前页面，未发送。',{exact:true}).waitFor();});
await test('data-table / filter no-results recovery sort and pagination',async()=>{await go('data-table');const input=page.getByRole('textbox',{name:'筛选演示课程'});await input.fill('no-match-999');assert(await page.getByText('没有匹配课程，请清除筛选。',{exact:true}).isVisible(),'no-match absent');await input.fill('');await page.locator('#specimen').getByRole('button',{name:'课程',exact:true}).click();assert(await page.locator('#specimen th[aria-sort="ascending"]').count()===1,'sort missing');await page.locator('#specimen').getByRole('button',{name:'下一页',exact:true}).click();assert((await page.locator('#specimen [role="status"]').innerText()).includes('2'),'pagination absent');});
await test('review regression / one main landmark and malformed hash recovery',async()=>{assert(await page.getByRole('main').count()===1,'nested main');await page.evaluate(()=>{location.hash='%'});await page.locator('#specimen[data-component-id="button"]').waitFor();assert(await page.getByRole('main').count()===1,'fallback landmark');});
await test('review regression / Command opens filters selects and restores focus',async()=>{await go('kbd');const trigger=page.getByRole('button',{name:/查找课程/});await trigger.click();const dialog=page.getByRole('dialog',{name:'查找演示课程'});await dialog.waitFor();const input=dialog.getByRole('combobox');await input.fill('no-result-999');await dialog.getByText('没有匹配项。',{exact:true}).waitFor();await input.fill('');const chosen=await dialog.getByRole('option').first().innerText();await input.press('ArrowDown');await input.press('Home');await input.press('Enter');await dialog.waitFor({state:'hidden'});assert(await trigger.evaluate(el=>el===document.activeElement),'selection focus restore');assert((await page.locator('#specimen [role="status"]').innerText()).includes(chosen),'selection absent');await trigger.focus();await page.keyboard.press('Control+k');await dialog.waitFor();await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert(await trigger.evaluate(el=>el===document.activeElement),'Escape focus restore');});
await test('review regression / navigation links preserve gallery route',async()=>{await go('navigation-menu');await page.locator('#specimen').getByRole('button',{name:'工作空间',exact:true}).click();await page.locator('#specimen').getByRole('link',{name:'练习',exact:true}).click();assert(new globalThis.URL(page.url()).hash==='#navigation-menu','sample link rerouted gallery');assert((await page.locator('#specimen [role="status"]').innerText()).includes('练习'),'local content unchanged');await page.keyboard.press('Escape');});
await test('320px / all 64 gallery entries have no page overflow',async()=>{await page.setViewportSize({width:320,height:844});const overflow=[];for(const entry of manifest.entries){await go(entry.id);const dims=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));if(dims.scroll>dims.viewport)overflow.push({id:entry.id,...dims});}assert(!overflow.length,JSON.stringify(overflow));return {checked:64,width:320}});
await test('mobile navigation / official sheet open Escape and component select',async()=>{await go('button');const trigger=page.getByRole('button',{name:'打开或关闭组件目录'});await trigger.click();await page.locator('[data-mobile="true"]').waitFor();await page.keyboard.press('Escape');await page.locator('[data-mobile="true"]').waitFor({state:'hidden'});await page.locator('#component-select').click();await page.getByRole('option',{name:'表单字段 / field',exact:true}).click();await page.locator('#specimen[data-component-id="field"]').waitFor();assert(await page.locator('#form-title').isVisible(),'mobile select route failed');});
await test('screenshots / desktop and narrow compositions',async()=>{await page.setViewportSize({width:1440,height:1000});for(const id of ['button','field','data-table','questionnaire']){await go(id);await screenshot('desktop-'+id)}await page.setViewportSize({width:320,height:844});await go('field');await screenshot('mobile-320-field');await page.setViewportSize({width:390,height:844});await go('button');await screenshot('mobile-390-button');await page.setViewportSize({width:768,height:1000});await go('dialog');await screenshot('tablet-dialog');return shots;});
await test('palette / computed text pairs and actual 50% ring blended contrast',async()=>{const colors=await page.evaluate(()=>{const cs=getComputedStyle(document.documentElement),keys=['background','foreground','primary','primary-foreground','accent','accent-foreground','muted','muted-foreground','input','ring'];return Object.fromEntries(keys.map(k=>[k,cs.getPropertyValue('--'+k).trim()]))});const rgb=h=>{let hex=h.replace('#','');if(hex.length===3)hex=[...hex].map(c=>c+c).join('');return hex.match(/../g).map(x=>parseInt(x,16)/255)},lum=a=>a.map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0),ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);const pairs=[['foreground','background'],['primary-foreground','primary'],['accent-foreground','accent'],['muted-foreground','background'],['muted-foreground','muted']].map(([a,b])=>({pair:a+'/'+b,ratio:ratio(rgb(colors[a]),rgb(colors[b]))}));assert(pairs.every(p=>p.ratio>=4.5),'text contrast failure');const ring=rgb(colors.ring).map((v,i)=>(v+rgb(colors.background)[i])/2),ringRatio=ratio(ring,rgb(colors.background));assert(ringRatio>=3,'ring under3: '+ringRatio);return {pairs,focusRing50Percent:ringRatio,inputBoundary:ratio(rgb(colors.input),rgb(colors.background)),caveat:'Official destructive variant has separate low-opacity error rings, unmodified; not a blanket WCAG certification'};});
await test('offline / self-contained file renders all entries, bundled fonts, no network',async()=>{await page.context().setOffline(true);await page.goto('file://'+path.join(OUT,'Wringy-Design-System.html'));await page.locator('#specimen').waitFor();const empty=[];for(const e of manifest.entries){await go(e.id);if(!(await page.locator('#specimen').evaluate(el=>el.children.length)))empty.push(e.id)}assert(!empty.length,'offline empty '+empty.join(','));await go('field');await page.locator('#form-submit').click();assert(await page.locator('#form-title').evaluate(el=>el===document.activeElement),'offline form behavior failed');await page.evaluate(()=>document.fonts.ready);const fonts=await page.evaluate(()=>[...document.fonts].map(f=>({family:f.family,status:f.status})));assert(fonts.some(f=>f.family.includes('Geist')&&f.status==='loaded'),'Geist font not loaded offline');await screenshot('offline-file');await page.context().setOffline(false);return {rendered:64,fontFaces:fonts};});
await test('runtime / no React or browser uncaught errors',async()=>{assert(!errors.length,errors.join('\n'));return errors});
const report={checkedAt:new Date().toISOString(),result:checks.every(c=>c.passed)?'passed':'failed',browser:'Project Playwright 1.62.1 / '+(process.env.PLAYWRIGHT_BROWSER || 'chrome'),nativeUI:61,guidePatterns:3,checks,uncaughtErrors:errors,screenshots:shots,limitations:['Only Chrome automated tests, no screen reader or real mobile device certification','Official upstream motion and state styling retained, including transition-all where shipped','This is documentation and local examples, not production auth/API/payment integration','No claim to exhaust every upstream prop or combined state']};fs.writeFileSync(path.join(OUT,'browser-verification.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log('RESULT',report.result,checks.filter(c=>c.passed).length+'/'+checks.length);process.exitCode=report.result==='passed'?0:1;
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1});
