"""Generate CSS only from tokens.json. References remain CSS variable aliases."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parent

def flatten(obj, prefix=''):
    for key, value in obj.items():
        name = f'{prefix}-{key}' if prefix else key
        if isinstance(value, dict):
            yield from flatten(value, name)
        else:
            yield name, value

def generate():
    data = json.loads((ROOT / 'tokens.json').read_text())
    lines = ['/* Generated by generate-tokens.py; edit tokens.json. */', ':root {']
    for layer in ('primitive', 'semantic', 'component'):
        for key, value in flatten(data[layer]):
            if isinstance(value, str) and value.startswith('{'):
                value = 'var(--' + value[1:-1].replace('.', '-') + ')'
            elif isinstance(value, (int, float)):
                value = f'{value}px'
            lines.append(f'  --{layer}-{key}: {value};')
    for name, rule in data['typography'].items():
        for key, value in rule.items():
            lines.append(f'  --type-{name}-{key}: {value}{"px" if key == "size" else ""};')
    lines.append('}')
    (ROOT / 'tokens.css').write_text('\n'.join(lines) + '\n')

if __name__ == '__main__':
    generate()

# Embed authoritative JSON so index.html works when opened directly.
# catalog.json belongs to the catalog worker; it is never modified here.
if __name__ == '__main__':
    import re
    html = (ROOT / 'index.html').read_text()
    for name in ('tokens', 'catalog', 'demo-data'):
        source = ROOT / f'{name}.json'
        if not source.exists():
            continue
        payload = source.read_text().replace('<', '\\u003c')
        block = f'<script type="application/json" id="embedded-{name}">{payload}</script>'
        pattern = rf'<script type="application/json" id="embedded-{name}">.*?</script>'
        if re.search(pattern, html, flags=re.S):
            html = re.sub(pattern, lambda _: block, html, flags=re.S)
        else:
            html = html.replace('</head>', block + '\n</head>')
    (ROOT / 'index.html').write_text(html)
    # Shared media queries use generated values; CSS custom properties cannot be
    # interpolated inside media query conditions in browsers.
    css = (ROOT / 'styles.css').read_text()
    data = json.loads((ROOT / 'tokens.json').read_text())
    breakpoints = data['primitive']['breakpoint']
    for name, default in [('mobile','700px'),('tablet','900px'),('desktop','1150px'),('wide','1600px')]:
        comparison = 'min' if name == 'wide' else 'max'
        marker = f'/* breakpoint:{name} */'
        if marker not in css:
            css = css.replace(f'@media({comparison}-width:{default})', marker + f'@media({comparison}-width:{breakpoints[name]})')
        else:
            css = re.sub(re.escape(marker) + r'@media\([^)]+\)', marker + f'@media({comparison}-width:{breakpoints[name]})', css)
    (ROOT / 'styles.css').write_text(css)
    import sys
    if '--standalone' in sys.argv:
        html = html.replace('<link rel="stylesheet" href="tokens.css">', '<style>' + (ROOT / 'tokens.css').read_text() + '</style>')
        html = html.replace('<link rel="stylesheet" href="styles.css">', '<style>' + css + '</style>')
        for script in ('extra-specimens.js', 'app.js'):
            path = ROOT / script
            if path.exists():
                html = html.replace(f'<script src="{script}" defer></script>', '<script defer>' + path.read_text().replace('</script', '<\\/script') + '</script>')
        # Inline scripts execute at their position even with defer; move them to
        # the body end while preserving extra-before-app order.
        scripts = re.findall(r'<script defer>.*?</script>', html, flags=re.S)
        html = re.sub(r'<script defer>.*?</script>', '', html, flags=re.S)
        html = html.replace('</body>', ''.join(scripts) + '</body>')
        (ROOT / 'Wringy-Design-System.html').write_text(html)
