/* Reusable HTML factories. Trusted demo copy only; caller-supplied text is escaped. */
window.Wringy = (()=>{
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=(label,tone='neutral')=>`<span class="badge ${esc(tone)}">${esc(label)}</span>`;
const button=(label,{variant='',state='',action='',full=false}={})=>`<button class="btn ${esc(variant)} ${full?'full':''} ${state==='focus'?'demo-focus':''}" ${state==='disabled'?'disabled':''} ${state==='loading'?'aria-busy="true" aria-disabled="true"':''} ${state?'data-state="'+esc(state)+'"':''} ${action?'data-action="'+esc(action)+'"':''}>${state==='loading'?'处理中…':esc(label)}</button>`;
const field=(id,label,{value='',placeholder='',type='text',state='',help='',required=false}={})=>`<div class="field"><label for="${id}">${esc(label)}${required?'（必填）':''}</label><input id="${id}" name="${id}" type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}" ${required?'required':''} ${state==='disabled'?'disabled':''} ${state==='readonly'?'readonly':''} ${state==='error'?'aria-invalid="true"':''} ${state==='focus'?'class="demo-focus"':''} ${help?'aria-describedby="'+id+'-help"':''}>${help?`<span id="${id}-help" class="${state==='error'?'error':'muted small'}">${esc(help)}</span>`:''}</div>`;
const facts=rows=>`<dl class="facts">${rows.map(([k,v])=>`<div class="kv"><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`;
const steps=(rows,current=1)=>`<ol class="step-list">${rows.map(([title,note],i)=>`<li ${i===current?'aria-current="step"':''}><span class="step-dot ${i<current?'done':i===current?'current':''}" aria-hidden="true">${i<current?'✓':i+1}</span><span class="step-copy"><strong>${esc(title)}</strong><span class="muted small">${esc(note)}</span></span></li>`).join('')}</ol>`;
const brand=()=>`<a class="brand-lock" href="index.html" aria-label="Wringy 组件参考首页"><img src="images/logo.png" alt="Wringy 原始概念标志"><strong>Wringy</strong></a>`;
const nav=(role='brand',active='活动')=>`<aside class="sidebar">${brand()}<div class="org-label">${role==='brand'?'示例品牌 A':'示例创作者 01'}<br><span class="muted caption">${role==='brand'?'品牌工作空间':'创作者工作空间'}</span></div><nav class="side-links" aria-label="${role==='brand'?'品牌':'创作者'}导航">${(role==='brand'?['概览','活动','提交','付款记录','设置']:['探索','我的合作','作品提交','报酬记录','设置']).map(x=>`<a href="#" data-demo-link class="${x===active?'active':''}" ${x===active?'aria-current="page"':''}>${x}</a>`).join('')}</nav><div class="side-footer">清楚的约定。<br>更自在的创作。<hr class="divider">示例数据 · 本地设计参考</div></aside>`;
const topbar=role=>`<header class="topbar"><div class="small muted">${role==='brand'?'品牌工作空间 / 活动':'创作者工作空间 / 我的合作'}</div><div class="row"><span class="screen-tag">示例数据</span><button class="btn ghost" data-theme-toggle aria-label="切换明暗主题">深色</button><span class="avatar" aria-label="示例用户">${role==='brand'?'A':'01'}</span></div></header>`;
const mobileHead=(role='brand')=>`<header class="mobile-head">${brand()}<span class="badge">${role==='brand'?'品牌端':'创作者端'} · 示例</span></header>`;
const bottomNav=(role='brand',active='提交')=>`<nav class="bottom-nav" aria-label="${role==='brand'?'品牌':'创作者'}底部导航">${(role==='brand'?['活动','提交','通知','我的']:['探索','合作','报酬','我的']).map(x=>`<a href="#" data-demo-link class="${x===active?'active':''}" ${x===active?'aria-current="page"':''}>${x}</a>`).join('')}</nav>`;
const reviewRow=(n=1,status='待审核',tone='info')=>`<article class="review-row"><span class="avatar" aria-hidden="true">0${n}</span><div class="grow"><h3>示例创作者 0${n}</h3><p>竖屏视频 · 版本 ${n===2?'2':'1'}</p><span class="caption muted">9月10日 ${n+10}:30 MYT</span></div><div class="stack tight">${badge(status,tone)}${button('查看作品',{variant:'ghost',action:'review-detail'})}</div></article>`;
const campaignCard=()=>`<article class="panel stack"><div class="spread">${badge('招募中','info')}<span class="caption muted">示例品牌 A</span></div><h3>把日常拍出新意</h3><p class="small muted">1 条 20–30 秒竖屏视频，让使用场景成为故事。</p>${facts([['固定报酬','MYR 150.00 / 条'],['截止时间','9月30日 18:00 MYT']])}${button('查看合作要求',{variant:'secondary',action:'brief'})}</article>`;
const payout=(state='processing')=>{const map={pending:['待品牌付款','warning','品牌直接向创作者付款。到账仍待确认。'],approved:['报酬已批准','success','批准不等于到账。请查看与品牌约定的付款条件。'],available:['可发起付款请求','info','未来集成路线示例；不代表首发钱包功能。'],processing:['服务方处理中','info','服务方已接收请求，银行到账尚待确认。'],failed:['付款未完成','danger','先核对服务方状态，再决定下一步；不要重复发起。'],paid:['到账已确认','success','仅在收到可靠到账确认后使用此状态。'],unknown:['状态待核对','warning','暂无可靠付款结果，请查看记录并联系支持。'],banned:['账户已封禁','danger','付款记录仍按允许范围提供；查看原因与申诉方式。']};const [label,tone,note]=map[state]||map.processing;return `<div class="stack">${badge(label,tone)}${facts([['款项总额','MYR 150.00'],['示例服务费','MYR 2.00'],['预计净到账','MYR 148.00']])}<div class="callout ${tone==='danger'?'danger':''}">${note}</div><p class="demo-only">未来集成路线 · 示例数据，非实际费率。首发为品牌直接付款。</p></div>`};
const screens={
 'UI-BRAND-DESKTOP':()=>`<div class="workspace">${nav('brand','活动')}<div class="work-main">${topbar('brand')}<main id="main" class="page-content"><div class="page-head"><div><h1>让下一次合作，<br>从清楚的简报开始。</h1><p>活动草稿 · 完善约定后，再邀请创作者。</p></div><div class="row">${button('保存草稿',{variant:'secondary',action:'save-draft-demo'})}${button('发布活动',{state:'disabled'})}</div></div><div class="overview-strip"><div><span class="label">计划预算 · 示例</span><div class="money"><small>MYR</small> 3,000.00</div><p class="small muted">草稿预算，不代表资金已入账</p></div><div><span class="label">单条固定报酬</span><div class="money"><small>MYR</small> 150.00</div><p class="small muted">品牌直接付款</p></div><div><span class="label">发布前待确认</span><div class="money">03 <small>项约定</small></div><p class="small muted">使用权、修改轮次、审核期限</p></div></div><div class="two-col"><section class="stack"><article class="campaign-cover"><div class="stack"><div class="row">${badge('草稿')}<span class="caption muted">示例活动 / 尚未发布</span></div><h2>把日常拍出新意</h2><p class="small muted">20–30 秒竖屏视频 · 创作者合作</p><div class="row"><span class="amount small"><strong>MYR 150.00</strong> / 条</span></div><span class="caption muted">计划截止：9月30日18:00 MYT</span></div><img src="images/editorial.png" alt="活动草稿概念影像，非真实创作者作品"></article><section class="panel stack"><h3>要求明确，创作更自在</h3>${facts([['交付数量','1条竖屏视频'],['必须包含','产品使用场景'],['自由发挥','开场与叙事方式'],['广告披露','须按最终活动要求添加']])}<div class="callout">这是未发布草稿，尚未邀请创作者或收到作品。</div></section></section><aside class="panel stack"><div class="spread"><h3>发布前检查</h3>${badge('发布已阻止','warning')}</div>${steps([['交付要求已填写','1条视频 · 产品使用场景'],['使用权待确认','请明确用途、范围与期限'],['修改轮次待确认','请明确反馈与修改次数'],['审核期限待确认','请给出双方可理解的时间要求']],1)}<hr class="divider"><div class="callout warning">请先确认使用权、修改轮次与审核期限，才能发布活动。</div>${button('完善合作条件',{variant:'secondary',action:'brief'})}<p class="demo-only">示例数据 · 仅演示草稿与发布阻止状态</p></aside></div></main></div></div>`,
'UI-BRAND-MOBILE':()=>`<div class="mobile-shell">${mobileHead('brand')}<main id="main" class="mobile-content"><div class="spread"><h1>待审核作品</h1>${badge('3 份','info')}</div><p class="small muted" style="margin-top:8px">把日常拍出新意 · 独立已发布示例</p><div class="panel section-gap"><div class="label">单条固定报酬</div><div class="mobile-stat"><strong class="amount">150.00</strong><span class="small">MYR / 条</span></div><p class="caption muted">品牌直接付款。通过审核不等于到账。</p></div><div class="tabs section-gap" role="tablist" aria-label="作品状态"><button class="tab" id="mq-tab1" role="tab" aria-selected="true" aria-controls="mq-panel1">待审核 3</button><button class="tab" id="mq-tab2" role="tab" aria-selected="false" tabindex="-1" aria-controls="mq-panel2">需修改 2</button></div><section id="mq-panel1" role="tabpanel" aria-labelledby="mq-tab1">${reviewRow(1)}${reviewRow(2)}${reviewRow(3)}</section><section id="mq-panel2" role="tabpanel" aria-labelledby="mq-tab2" hidden>${reviewRow(2,'需修改','warning')}<p class="small muted">请补充产品使用场景，再次提交。</p></section></main>${bottomNav('brand','提交')}</div>`,
'UI-CREATOR-DESKTOP':()=>`<div class="workspace">${nav('creator','我的合作')}<div class="work-main">${topbar('creator')}<main id="main" class="page-content"><div class="page-head"><div><div class="row small muted"><span>我的合作</span><span>/</span><span>作品详情</span></div><h1 style="margin-top:12px">每一次创作，<br>都有清楚的下一步。</h1></div>${button('查看活动简报',{variant:'secondary',action:'brief'})}</div><div class="two-col"><section class="stack"><article class="panel stack"><div class="spread"><div><span class="caption muted">示例品牌 A</span><h2>把日常拍出新意</h2></div>${badge('审核已批准','success')}</div><img class="preview-art" src="images/editorial.png" alt="创作桌面概念影像，作为示例作品预览"><div class="spread"><div><strong>周末创作手记 · 版本 2</strong><p class="small muted">竖屏视频 · 26 秒 · 9月10日提交</p></div>${button('查看提交回执',{variant:'ghost',action:'submission-receipt'})}</div></article><article class="panel stack"><h3>要求与反馈，都有依据</h3><div class="row">${badge('✓ 使用场景已包含','success')}${badge('✓ 时长符合要求','success')}${badge('✓ 披露文字已添加','success')}</div><p class="small">“已符合本次示例简报要求。感谢你把日常使用拍成有趣的故事。”</p><span class="caption muted">示例审核意见 · 9月12日 14:30 MYT</span></article></section><aside class="stack"><section class="panel stack"><span class="label">本次合作报酬</span><div class="money"><small>MYR</small> 150.00</div>${badge('已批准 · 待品牌付款','warning')}<p class="small muted">品牌直接付款。审核批准不等于银行到账。</p><hr class="divider">${facts([['付款状态','等待品牌付款'],['到账日期','尚未确认'],['记录来源','合作双方确认']])}${button('查看付款约定',{variant:'secondary',action:'payment-agreement'})}</section><section class="panel stack"><h3>合作记录</h3>${steps([['作品已提交','9月10日 · 已收到回执'],['审核已批准','9月12日 · 要求已满足'],['等待品牌付款','到账信息待确认']],2)}<p class="demo-only">示例数据 · 不代表真实收入</p></section></aside></div></main></div></div>`,
 'UI-CREATOR-MOBILE':()=>`<div class="mobile-shell">${mobileHead('creator')}<main id="main" class="mobile-content"><div class="spread"><h1>报酬详情</h1><span class="screen-tag">示例数据</span></div><p class="small muted" style="margin:8px 0 16px">把日常拍出新意 · 示例品牌 A</p><section class="reward-hero"><div class="label">已批准报酬</div><div class="money"><small>MYR</small> 150.00</div>${badge('已批准 · 待品牌付款','warning')}<p class="small muted" style="margin-top:12px">品牌直接付款。审核批准不等于银行到账。</p></section><section class="panel section-gap"><h3 style="margin-bottom:16px">下一步，等待付款确认</h3>${facts([['付款方','示例品牌 A'],['款项金额','MYR 150.00'],['到账状态','尚未确认'],['预计到账','时间尚未提供']])}<hr class="divider"><p class="small muted">这不是平台可提现余额；不提供提现操作。</p></section><div class="stack section-gap">${button('查看付款约定',{variant:'secondary',full:true,action:'payment-agreement'})}<p class="demo-only">示例记录 · 不代表真实收入或交易</p></div></main>${bottomNav('creator','报酬')}</div>`,
'UI-PAYOUT-CONFIRM':()=>`<div class="mobile-shell">${mobileHead('creator')}<main id="main" class="mobile-content"><div class="spread"><h1>报酬详情</h1><span class="screen-tag">示例数据</span></div><p class="small muted" style="margin:8px 0 16px">把日常拍出新意</p><span class="future-label">未来集成路线示例 · 首发为品牌直接付款</span><section class="reward-hero"><div class="label">预计净到账</div><div class="money"><small>MYR</small> 148.00</div>${badge('服务方处理中','info')}<p class="small muted" style="margin-top:12px">请求已接收，银行到账尚未确认。</p></section><section class="panel section-gap"><h3 style="margin-bottom:16px">每个金额，都写清楚</h3>${facts([['款项总额','MYR 150.00'],['示例服务费','− MYR 2.00'],['预计净到账','MYR 148.00']])}<hr class="divider"><p class="caption muted">示例，非实际费率；不代表首发钱包功能。</p></section><div class="stack section-gap">${facts([['收款账户','示例账户 •••• 1234'],['预计到账','时间尚未提供']])}${button('查看服务方记录',{variant:'secondary',full:true,action:'provider-record'})}<p class="demo-only">状态未知时先核对记录，不重复发起。</p></div></main>${bottomNav('creator','报酬')}</div>`
};
return {esc,badge,button,field,facts,steps,brand,nav,reviewRow,campaignCard,payout,screens};
})();
