import {createRequire} from 'node:module';import {pathToFileURL,fileURLToPath} from 'node:url';import path from 'node:path';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire('${HOME}/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');const{chromium}=require('playwright');const root=path.dirname(fileURLToPath(import.meta.url)),out=path.resolve(root,'../../assets/ui');const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const p=await browser.newPage({viewport:{width:1440,height:1000}});await p.goto(pathToFileURL(path.join(root,'index.html')).href);await p.evaluate(()=>document.fonts.ready);
const c=await p.evaluate(()=>WRINGY_CATALOG.map(({id,name,renderedStates,renderedVariants,interactions})=>({id,name,renderedStates,renderedVariants,interactions})));await fs.writeFile(path.join(root,'implementation-coverage.json'),JSON.stringify(c,null,2));
for(const theme of ['light','dark']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const id of ['upload','form','checkbox-radio-switch','notification-center','onboarding','campaign-brief','reward-ledger','chart'])await p.locator('#'+id).screenshot({path:path.join(out,'catalog',id+'-'+theme+'.png')});}
const a=await p.evaluate(()=>({unlabelled:[...document.querySelectorAll('input,select,textarea')].filter(n=>!n.labels?.length&&!n.getAttribute('aria-label')&&!n.getAttribute('aria-labelledby')).map(n=>n.id),missingImageAlt:[...document.images].filter(n=>!n.hasAttribute('alt')).length,fonts:document.fonts.check('16px Manrope')&&document.fonts.check('16px "Noto Sans SC"')}));assert.deepEqual(a.unlabelled,[]);assert.equal(a.missingImageAlt,0);assert.equal(a.fonts,true);
const sw=p.locator('#checkbox-radio-switch [role=switch]');await sw.focus();await p.keyboard.press('Space');assert.equal(await sw.isChecked(),false);await p.keyboard.press('Space');assert.equal(await sw.isChecked(),true);const focus=await sw.evaluate(n=>({style:getComputedStyle(n).outlineStyle,width:getComputedStyle(n).outlineWidth}));assert.notEqual(focus.style,'none');
await p.locator('#file-demo').setInputFiles({name:'sample.png',mimeType:'image/png',buffer:Buffer.from('local design test')});assert.match(await p.locator('#file-status').textContent(),/仅显示文件名/);
await p.locator('#onboarding [data-action=onboard-next]').click();await p.locator('#onboarding [data-action=onboard-next]').click();assert.match(await p.locator('[data-step-copy]').textContent(),/第 3 步/);
const report=JSON.parse(await fs.readFile(path.join(out,'verification-report.json'),'utf8'));report.additionalAccessibilitySmoke={...a,switchKeyboard:true,visibleFocus:focus,uploadFilenameOnly:true,onboardingStep3:true};report.checks.push('Visible control labels, image alt, local fonts, switch Space/focus, valid file selection and onboarding step3');await fs.writeFile(path.join(out,'verification-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.additionalAccessibilitySmoke));await browser.close();
