"""Generate read-only projections from ../tokens.json. Run after canonical changes."""
from pathlib import Path
import json,hashlib
p=Path(__file__).resolve().parent;t=json.loads((p.parent/'tokens.json').read_text())
lines=['/* GENERATED from ../tokens.json; do not edit this file. */']
lines.append(':root {')
for g in ['color','space','radius','borderWidth','duration','easing','zIndex','breakpoint']:
 for k,v in t['primitive'][g].items():
  unit='px' if g in ['space','radius','borderWidth','breakpoint'] else 'ms' if g=='duration' else ''
  lines.append(f'--{g}-{k}:{v}{unit};')
for k,v in t['typography']['styles'].items():
 for mode in ['desktop','mobile']:lines.append(f'--type-{k}-{mode}:{v[mode]}px;')
 lines.append(f'--weight-{k}:{v["weight"]};--leading-{k}:{v.get("cjkLineHeight",v["lineHeight"])};')
for k,v in t['layout'].items():
 if isinstance(v,(int,float)):lines.append(f'--layout-{k}:{v}px;')
lines.append('}')
for mode in ['light','dark']:
 lines.append((':root,[data-theme="light"]' if mode=='light' else '[data-theme="dark"]')+'{color-scheme:'+mode+';')
 for k,v in t['semantic'][mode].items():lines.append('--'+k.replace('.','-')+':var(--color-'+v.split('.')[-1][:-1]+');')
 for k,v in t['shadow'][mode].items():lines.append(f'--shadow-{k}:{v};')
 lines.append('}')
(p/'tokens.css').write_text('\n'.join(lines))
(p/'tokens.json').write_text(json.dumps(t,ensure_ascii=False,indent=2))
(p/'tokens-data.js').write_text('window.WRINGY_TOKENS='+json.dumps(t,ensure_ascii=False)+';')
(p/'token-provenance.json').write_text(json.dumps({'canonical':'../tokens.json','sha256':hashlib.sha256((p.parent/'tokens.json').read_bytes()).hexdigest(),'projection':'tokens.css, tokens.json, tokens-data.js are generated, never independently edited.'},indent=2))
