import {createRequire} from 'node:module';import {pathToFileURL,fileURLToPath} from 'node:url';import path from 'node:path';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire('${HOME}/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');const {chromium}=require('playwright');const root=path.dirname(fileURLToPath(import.meta.url)),out=path.resolve(root,'../../assets/ui');await fs.mkdir(path.join(out,'catalog'),{recursive:true});const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const url=pathToFileURL(path.join(root,'index.html')).href;const report={errors:[],checks:[],screenshots:[],responsive:[]};const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>report.errors.push(e.message));const network=[];page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url())});await page.goto(url);await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('[data-family]').count(),31);report.checks.push('31 named families rendered');
const coverage=await page.evaluate(()=>WRINGY_CATALOG.map(({id,name,renderedStates,renderedVariants,interactions})=>({id,name,renderedStates,renderedVariants,interactions})));await fs.writeFile(path.join(root,'implementation-coverage.json'),JSON.stringify(coverage,null,2));
for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.screenshot({path:path.join(out,'catalog-'+theme+'.png'),fullPage:false});for(const family of coverage){const locator=page.locator('[data-family="'+family.id+'"]');const output=path.join(out,'catalog',family.id+'-'+theme+'.png');if(process.env.SKIP_RENDER!=='1')await locator.screenshot({path:output});report.screenshots.push(output);}await page.locator('#foundations').screenshot({path:path.join(out,'foundations-'+theme+'.png')});}
await page.evaluate(()=>document.documentElement.dataset.theme='light');
await page.locator('#sample-form button[type=submit]').click();assert.equal(await page.locator('#form-errors').isVisible(),true);assert.equal(await page.evaluate(()=>document.activeElement.id),'form-errors');await page.locator('#form-name').fill('示例活动');await page.locator('#form-email').fill('creator@example.com');await page.locator('#form-terms').check();await page.locator('#sample-form button[type=submit]').click();assert.match(await page.locator('#form-result').textContent(),/验证通过/);report.checks.push('Form error summary/focus + valid local submission');
const modalButton=page.locator('#modal [data-action=modal-demo]');await modalButton.click();assert.equal(await page.locator('#demo-dialog').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#demo-dialog').isVisible(),false);assert.equal(await modalButton.evaluate(n=>n===document.activeElement),true);report.checks.push('Dialog opens, Escape closes, focus restored');
await page.locator('#dropdown [data-menu-trigger]').click();assert.equal(await page.locator('#action-menu').isVisible(),true);await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'复制示例链接');await page.keyboard.press('Escape');assert.equal(await page.locator('#action-menu').isVisible(),false);report.checks.push('Menu arrow navigation + Escape');
await page.locator('#detail-tab1').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#detail-panel2').isVisible(),true);report.checks.push('Tabs keyboard switch visible panel');
await page.locator('#catalog-search').fill('无匹配词');assert.match(await page.locator('#search-results').textContent(),/没有匹配/);await page.locator('#search-filter [data-action=clear-filter]').click();assert.match(await page.locator('#search-results').textContent(),/2个/);report.checks.push('Search no-results and clear');
await page.locator('#file-demo').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('sample')});assert.match(await page.locator('#file-status').textContent(),/不符合/);report.checks.push('Upload invalid type preserves honest local-only status');
for(const state of ['pending','approved','available','processing','failed','paid','unknown','banned']){await page.locator('#payout-state').selectOption(state);const txt=await page.locator('#payout-state-panel').textContent();assert.match(txt,/148\.00/);assert.match(txt,/未来集成/);await page.locator('#payout-flow').screenshot({path:path.join(out,'catalog','payout-state-'+state+'.png')});}
for(const state of ['draft','submitted','reviewing','changes-requested','approved','rejected']){await page.locator('#submission-state').selectOption(state);await page.locator('#submission').screenshot({path:path.join(out,'catalog','submission-state-'+state+'.png')});}report.checks.push('8 payout and6 submission states switched and separately rendered');
const ids=await page.evaluate(()=>[...document.querySelectorAll('[id]')].map(n=>n.id));assert.equal(ids.length,new Set(ids).size);report.checks.push('No duplicate live IDs; template content inert');
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.goto(url);await page.evaluate(()=>document.fonts.ready);const metrics=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));report.responsive.push({view:'catalog',...metrics});assert.equal(metrics.width,metrics.scrollWidth,'catalog width '+width);await page.screenshot({path:path.join(out,'catalog-'+width+'.png')});}
for(const name of Object.keys((await page.evaluate(()=>Object.fromEntries(Object.keys(Wringy.screens).map(k=>[k,true])))))){for(const width of [320,name.endsWith('DESKTOP')?1440:390]){await page.setViewportSize({width,height:name.endsWith('DESKTOP')?1000:844});await page.goto(url+'?screen='+name+'&theme=dark');await page.evaluate(()=>document.fonts.ready);const metrics=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));report.responsive.push({view:name,...metrics});assert.equal(metrics.width,metrics.scrollWidth,name+' width '+width);await page.screenshot({path:path.join(out,name+'-dark-'+width+'.png')});}}
await page.goto(url);await page.evaluate(()=>document.fonts.ready);await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('.btn')).transitionDuration),'0s');report.checks.push('Reduced motion removes transitions');report.externalNetworkRequests=network;assert.equal(network.length,0);assert.equal(report.errors.length,0);report.checks.push('No external requests and no JS runtime errors');report.limitations=['Automated browser checks are not WCAG certification or full screen-reader testing.','Specification-only combinations remain distinct from implementation coverage.'];await fs.writeFile(path.join(out,'verification-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({checks:report.checks,responsive:report.responsive,screenshots:report.screenshots.length,errors:report.errors},null,2));await browser.close();
