import { useRef, useState, type FormEvent } from 'react'
import { AlertCircleIcon, CheckIcon, ChevronDownIcon, FolderIcon, PlusIcon, SearchIcon } from 'lucide-react'
import { toast } from 'sonner'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog'
import { AspectRatio } from '@/components/ui/aspect-ratio'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from '@/components/ui/breadcrumb'
import { Button } from '@/components/ui/button'
import { ButtonGroup, ButtonGroupText } from '@/components/ui/button-group'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from '@/components/ui/empty'
import { Field, FieldContent, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldLegend, FieldSet } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { InputGroup, InputGroupAddon, InputGroupInput, InputGroupText, InputGroupTextarea } from '@/components/ui/input-group'
import { InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot } from '@/components/ui/input-otp'
import { Item, ItemActions, ItemContent, ItemDescription, ItemGroup, ItemMedia, ItemTitle } from '@/components/ui/item'
import { Label } from '@/components/ui/label'
import { NativeSelect, NativeSelectOptGroup, NativeSelectOption } from '@/components/ui/native-select'
import { Progress } from '@/components/ui/progress'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Separator } from '@/components/ui/separator'
import { Skeleton } from '@/components/ui/skeleton'
import { Slider } from '@/components/ui/slider'
import { Spinner } from '@/components/ui/spinner'
import { Switch } from '@/components/ui/switch'
import { Textarea } from '@/components/ui/textarea'
import { Toggle } from '@/components/ui/toggle'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { Questionnaire, QuestionnaireActions, QuestionnaireChoice, QuestionnaireChoices, QuestionnaireDescription, QuestionnaireError, QuestionnaireItem, QuestionnaireNext, QuestionnairePrevious, QuestionnaireProgress, QuestionnaireSkip, QuestionnaireSubmit, QuestionnaireTitle } from '@/components/ui/questionnaire'

export const coreStates: Record<string, string[]> = {
  accordion:['live','open','disabled'], alert:['live','destructive'], 'alert-dialog':['live'],
  'aspect-ratio':['live'],avatar:['live','fallback'],badge:['live'],breadcrumb:['live'],button:['live','disabled','loading'],
  'button-group':['live','disabled'],card:['live'],checkbox:['unchecked','checked','indeterminate','disabled','invalid'],collapsible:['live','open','disabled'],
  empty:['empty','no-results'],field:['live'],input:['live','disabled','readonly','invalid'],
  'input-group':['live','disabled','invalid'],'input-otp':['live','disabled','invalid'],item:['live'],label:['live'],
  'native-select':['live','disabled','invalid'],progress:['live','complete','indeterminate'],'radio-group':['live','disabled','invalid'],
  separator:['live'],skeleton:['live'],slider:['live','disabled'],spinner:['live'],switch:['off','on','disabled','invalid'],
  textarea:['live','disabled','readonly','invalid'],toggle:['live','pressed','disabled'],'toggle-group':['live','selected','disabled'],questionnaire:['live'],typography:['live'],
}
export const stateLabels:Record<string,string>={live:'直接操作',open:'默认展开',disabled:'禁用',destructive:'错误提示',fallback:'头像回退',loading:'处理中',unchecked:'未选中',checked:'选中',indeterminate:'不确定 / 部分',invalid:'校验错误',empty:'首次空态','no-results':'筛选无结果',readonly:'只读',complete:'完成',off:'关闭',on:'开启',pressed:'选中',selected:'已选择'}
export type ButtonVariant='default'|'outline'|'secondary'|'ghost'|'destructive'|'link'

export function CoreExample({id,state='live',variant='default'}:{id:string,state?:string,variant?:ButtonVariant}) {
  const disabled=state==='disabled', invalid=state==='invalid'
  const [checked,setChecked]=useState<boolean|'indeterminate'>(state==='indeterminate'?'indeterminate':state==='checked')
  const [switched,setSwitched]=useState(state==='on')
  const [count,setCount]=useState(1)
  const [slider,setSlider]=useState([40])
  const [range,setRange]=useState([20,80])
  const [radio,setRadio]=useState('all')
  const [toggle,setToggle]=useState(state==='pressed')
  const [group,setGroup]=useState(state==='selected'?'mine':'all')
  const [text,setText]=useState('')
  const [otp,setOtp]=useState('')
  const [qResult,setQResult]=useState('')
  switch(id){
    case 'button':return <div className="flex flex-col gap-6"><div className="flex flex-wrap gap-3"><Button id="button-demo" variant={variant} disabled={disabled||state==='loading'} aria-busy={state==='loading'} onClick={()=>toast('本地演示操作已触发')}>{state==='loading'?<Spinner data-icon="inline-start"/>:<PlusIcon data-icon="inline-start"/>}{state==='loading'?'正在保存…':'添加作品'}</Button><Button variant="outline" disabled={disabled} onClick={()=>toast('次要操作已触发')}>取消</Button></div><div className="flex flex-wrap gap-3">{(['default','outline','secondary','ghost','destructive','link'] as const).map(v=><Button key={v} variant={v} disabled={disabled} onClick={()=>toast(v+' 变体')}>{v}</Button>)}</div><FieldDescription>悬停、按下与键盘焦点由原组件自然呈现。加载使用官方 Spinner + disabled。</FieldDescription></div>
    case 'accordion':return <Accordion type="single" collapsible defaultValue={state==='open'?'requirements':undefined}><AccordionItem value="requirements" disabled={disabled}><AccordionTrigger>作品需要满足哪些要求？</AccordionTrigger><AccordionContent>主体清楚、使用过程完整。请核对活动已公布的要求版本。</AccordionContent></AccordionItem><AccordionItem value="scope"><AccordionTrigger>本地示例会提交内容吗？</AccordionTrigger><AccordionContent>不会。这里仅演示官方组件的展开与键盘行为。</AccordionContent></AccordionItem></Accordion>
    case 'alert':return <Alert variant={state==='destructive'?'destructive':'default'}><AlertCircleIcon/><AlertTitle>{state==='destructive'?'读取失败':'审核说明已更新'}</AlertTitle><AlertDescription>{state==='destructive'?'暂时无法读取最新内容。已有内容保留，请重试。':'本示例只在当前页面展示消息，不提交真实审核。'}</AlertDescription></Alert>
    case 'alert-dialog':return <AlertDialog><AlertDialogTrigger asChild><Button variant="outline">移除示例草稿</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>移除这份演示草稿？</AlertDialogTitle><AlertDialogDescription>这是本地确认对话框；不会删除真实文件或记录。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={()=>toast('确认已完成（本地演示）')}>确认移除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    case 'aspect-ratio':return <div className="w-full max-w-md"><AspectRatio ratio={16/9}><Skeleton className="size-full"/></AspectRatio><FieldDescription>16:9 媒体占位，比例由官方 AspectRatio 管理。</FieldDescription></div>
    case 'avatar':return <div className="flex items-center gap-4"><Avatar><AvatarImage src={state==='fallback'?'data:image/png;base64,invalid':undefined} alt="示例创作者"/><AvatarFallback>WA</AvatarFallback></Avatar><Avatar><AvatarFallback>WB</AvatarFallback></Avatar><FieldDescription>无图片时显示姓名缩写；不使用虚构客户照片。</FieldDescription></div>
    case 'badge':return <div className="flex flex-wrap gap-3"><Badge>默认</Badge><Badge variant="secondary">待审核</Badge><Badge variant="outline">尚未确认</Badge><Badge variant="destructive">需修改</Badge></div>
    case 'breadcrumb':return <Breadcrumb><BreadcrumbList><BreadcrumbItem><BreadcrumbLink href="#button">设计系统</BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator/><BreadcrumbItem><BreadcrumbLink href="#card">组件</BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator/><BreadcrumbItem><BreadcrumbPage>面包屑</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb>
    case 'button-group':return <div className="flex flex-col gap-4"><ButtonGroup aria-label="调整示例数量"><Button variant="outline" disabled={disabled||count===0} onClick={()=>setCount(c=>c-1)}>减少</Button><ButtonGroupText aria-live="polite">{count}</ButtonGroupText><Button variant="outline" disabled={disabled} onClick={()=>setCount(c=>c+1)}>增加</Button></ButtonGroup><FieldDescription>分组只组织相关动作，按钮几何保持官方默认。</FieldDescription></div>
    case 'card':return <Card className="w-full max-w-md"><CardHeader><CardTitle>水瓶使用演示</CardTitle><CardDescription>示例作品 · 内容审阅</CardDescription></CardHeader><CardContent><FieldDescription>核对主体、使用过程及授权范围，不从审核结果推导付款。</FieldDescription></CardContent><CardFooter><Button variant="outline" onClick={()=>toast('已打开本地作品说明')}>查看说明</Button></CardFooter></Card>
    case 'checkbox':return <FieldGroup><Field orientation="horizontal" data-invalid={invalid} data-disabled={disabled}><Checkbox id="checkbox-demo" checked={checked} onCheckedChange={setChecked} disabled={disabled} aria-invalid={invalid} aria-describedby={invalid?'checkbox-error':undefined}/><FieldContent><FieldLabel htmlFor="checkbox-demo">接收作品更新</FieldLabel><FieldDescription>当前：{checked==='indeterminate'?'部分选中':checked?'已选中':'未选中'}</FieldDescription>{invalid&&<FieldError id="checkbox-error">请确认此选择。</FieldError>}</FieldContent></Field></FieldGroup>
    case 'collapsible':return <Collapsible defaultOpen={state==='open'} disabled={disabled}><div className="flex items-center justify-between gap-3"><Label>作品附件</Label><CollapsibleTrigger asChild><Button variant="ghost" size="icon" aria-label="展开附件"><ChevronDownIcon/></Button></CollapsibleTrigger></div><CollapsibleContent><ItemGroup><Item><ItemContent><ItemTitle>授权说明.pdf</ItemTitle><ItemDescription>示例附件，不提供真实文件</ItemDescription></ItemContent></Item></ItemGroup></CollapsibleContent></Collapsible>
    case 'empty':return <Empty><EmptyHeader><EmptyMedia variant="icon"><FolderIcon/></EmptyMedia><EmptyTitle>{state==='no-results'?'没有匹配的作品':'还没有作品'}</EmptyTitle><EmptyDescription>{state==='no-results'?'当前筛选条件仍然保留。可以清除条件再试。':'提交的作品会显示在这里。本示例没有真实数据。'}</EmptyDescription></EmptyHeader><EmptyContent><Button variant="outline" onClick={()=>toast(state==='no-results'?'已清除示例筛选':'示例入口已触发')}>{state==='no-results'?'清除筛选':'查看提交要求'}</Button></EmptyContent></Empty>
    case 'field':return <FieldExample/>
    case 'input':return <FieldGroup><Field data-disabled={disabled} data-invalid={invalid}><FieldLabel htmlFor="input-demo">作品标题</FieldLabel><Input id="input-demo" placeholder="例如：水瓶使用演示" disabled={disabled} readOnly={state==='readonly'} aria-invalid={invalid} defaultValue={state==='readonly'?'只读作品标题':undefined} aria-describedby="input-help"/><FieldDescription id="input-help">{state==='readonly'?'可以选择和复制，不能编辑。':'标题与字段关联；输入不会发送到服务器。'}</FieldDescription>{invalid&&<FieldError>请输入作品标题。</FieldError>}</Field></FieldGroup>
    case 'input-group':return <FieldGroup><Field data-invalid={invalid}><FieldLabel htmlFor="group-demo">搜索作品</FieldLabel><InputGroup><InputGroupInput id="group-demo" placeholder="输入关键词" disabled={disabled} aria-invalid={invalid} value={text} onChange={e=>setText(e.target.value)}/><InputGroupAddon><SearchIcon/></InputGroupAddon><InputGroupAddon align="inline-end"><InputGroupText>{text.length} 字</InputGroupText></InputGroupAddon></InputGroup>{invalid&&<FieldError>请缩短搜索条件后重试。</FieldError>}</Field><Field><FieldLabel htmlFor="group-note">补充说明</FieldLabel><InputGroup><InputGroupTextarea id="group-note" placeholder="写下作品说明" disabled={disabled}/><InputGroupAddon align="block-end"><InputGroupText>本地草稿</InputGroupText></InputGroupAddon></InputGroup></Field></FieldGroup>
    case 'input-otp':return <FieldGroup><Field data-invalid={invalid}><FieldLabel htmlFor="otp-demo">六位验证码（仅演示）</FieldLabel><InputOTP id="otp-demo" maxLength={6} disabled={disabled} aria-invalid={invalid} value={otp} onChange={setOtp}><InputOTPGroup>{[0,1,2].map(i=><InputOTPSlot key={i} index={i} aria-invalid={invalid}/>)}</InputOTPGroup><InputOTPSeparator/><InputOTPGroup>{[3,4,5].map(i=><InputOTPSlot key={i} index={i} aria-invalid={invalid}/>)}</InputOTPGroup></InputOTP><FieldDescription>可键盘输入或粘贴；不会发送或校验真实验证码。</FieldDescription>{invalid&&<FieldError>验证码格式不正确。</FieldError>}</Field></FieldGroup>
    case 'item':return <ItemGroup><Item variant="outline"><ItemMedia variant="icon"><FolderIcon/></ItemMedia><ItemContent><ItemTitle>审核资料</ItemTitle><ItemDescription>要求、作品版本和证据摘要</ItemDescription></ItemContent><ItemActions><Button variant="outline" size="sm" onClick={()=>toast('已查看演示资料')}>查看</Button></ItemActions></Item><Item variant="muted"><ItemContent><ItemTitle>示例创作者 A</ItemTitle><ItemDescription>资料尚未核验</ItemDescription></ItemContent></Item></ItemGroup>
    case 'label':return <FieldGroup><Field><Label htmlFor="label-demo">通知邮箱</Label><Input id="label-demo" type="email" placeholder="name@example.com"/></Field><FieldDescription>点击标签会将焦点移到对应输入框。</FieldDescription></FieldGroup>
    case 'native-select':return <FieldGroup><Field data-disabled={disabled} data-invalid={invalid}><FieldLabel htmlFor="native-demo">审核范围</FieldLabel><NativeSelect id="native-demo" disabled={disabled} aria-invalid={invalid} value={radio} onChange={e=>setRadio(e.target.value)}><NativeSelectOptGroup label="审核队列"><NativeSelectOption value="all">全部作品</NativeSelectOption><NativeSelectOption value="mine">分配给我</NativeSelectOption><NativeSelectOption value="archived" disabled>已归档（不可用）</NativeSelectOption></NativeSelectOptGroup></NativeSelect>{invalid&&<FieldError>请选择有效范围。</FieldError>}<FieldDescription>浏览器原生弹出列表，保留操作系统行为。</FieldDescription></Field></FieldGroup>
    case 'progress':return <FieldGroup><Field><FieldLabel>读取进度</FieldLabel><Progress value={state==='indeterminate'?null:state==='complete'?100:slider[0]} aria-label="读取进度"/><FieldDescription>{state==='indeterminate'?'总量尚未确认':`${state==='complete'?100:slider[0]}% · 演示进度`}</FieldDescription>{state==='live'&&<Button variant="outline" onClick={()=>setSlider(([v])=>[Math.min(100,v+20)])}>推进 20%</Button>}</Field></FieldGroup>
    case 'radio-group':return <FieldSet><FieldLegend>审核视图</FieldLegend><RadioGroup value={radio} onValueChange={setRadio} disabled={disabled} aria-invalid={invalid}>{[['all','全部作品'],['mine','分配给我'],['pending','待处理']].map(([v,l])=><Field key={v} orientation="horizontal" data-invalid={invalid} data-disabled={disabled}><RadioGroupItem id={`radio-${v}`} value={v}/><FieldLabel htmlFor={`radio-${v}`}>{l}</FieldLabel></Field>)}</RadioGroup>{invalid&&<FieldError>请选择允许的审核范围。</FieldError>}</FieldSet>
    case 'separator':return <div className="flex flex-col gap-4"><Label>作品内容</Label><Separator/><FieldDescription>水平分隔关联段落。</FieldDescription><div className="flex h-8 items-center gap-4"><span>要求</span><Separator orientation="vertical"/><span>证据</span><Separator orientation="vertical"/><span>记录</span></div></div>
    case 'skeleton':return <div className="flex items-center gap-4" role="status" aria-label="正在读取内容"><Skeleton className="size-12"/><div className="flex w-full flex-col gap-2"><Skeleton className="h-4 w-3/4"/><Skeleton className="h-4 w-1/2"/></div></div>
    case 'slider':return <FieldSet disabled={disabled}><FieldLegend>预览缩放范围 · {range[0]}%–{range[1]}%</FieldLegend><FieldDescription>Minimum 为范围下限，Maximum 为范围上限。使用方向键或拖动调整。</FieldDescription><Slider value={range} onValueChange={setRange} min={0} max={100} step={10} disabled={disabled}/><FieldDescription>沿用 Radix 双滑块的原生名称；官方封装未提供单滑块名称入口，本页不修改组件源码。</FieldDescription></FieldSet>
    case 'spinner':return <div className="flex flex-wrap items-center gap-4" role="status"><Spinner/><span>正在读取作品…</span><Button disabled><Spinner data-icon="inline-start"/>处理中</Button></div>
    case 'switch':return <FieldGroup><Field orientation="horizontal" data-invalid={invalid} data-disabled={disabled}><Switch id="switch-demo" checked={switched} onCheckedChange={setSwitched} disabled={disabled} aria-invalid={invalid}/><FieldContent><FieldLabel htmlFor="switch-demo">作品更新提醒</FieldLabel><FieldDescription>{switched?'提醒已开启':'提醒已关闭'}</FieldDescription>{invalid&&<FieldError>无法更新设置，请重试。</FieldError>}</FieldContent></Field></FieldGroup>
    case 'textarea':return <FieldGroup><Field data-invalid={invalid} data-disabled={disabled}><FieldLabel htmlFor="textarea-demo">作品说明</FieldLabel><Textarea id="textarea-demo" placeholder="描述完整使用过程" disabled={disabled} readOnly={state==='readonly'} defaultValue={state==='readonly'?'这是一份可复制的只读说明。':undefined} aria-invalid={invalid}/>{invalid&&<FieldError>请补充作品说明。</FieldError>}</Field></FieldGroup>
    case 'toggle':return <div className="flex flex-col gap-4"><Toggle aria-label="置顶作品" pressed={toggle} onPressedChange={setToggle} disabled={disabled} variant="outline"><CheckIcon data-icon="inline-start"/>置顶</Toggle><FieldDescription>{toggle?'作品已在本地示例中置顶':'尚未置顶'}</FieldDescription></div>
    case 'toggle-group':return <FieldGroup><Field><FieldLabel id="view-toggle-label">查看范围</FieldLabel><ToggleGroup type="single" value={group} onValueChange={v=>v&&setGroup(v)} disabled={disabled} variant="outline" aria-labelledby="view-toggle-label"><ToggleGroupItem value="all">全部</ToggleGroupItem><ToggleGroupItem value="mine">我的</ToggleGroupItem><ToggleGroupItem value="pending">待审</ToggleGroupItem></ToggleGroup><FieldDescription>单选组使用官方选中状态，不模拟按钮配色。</FieldDescription></Field></FieldGroup>
    case 'questionnaire':{const questions=[{name:'role',required:true,prompt:'你主要以哪种身份使用？',description:'选项仅用于演示，不创建账号。',choices:[{value:'creator',label:'创作者'},{value:'brand',label:'品牌审核员'}]},{name:'focus',required:false,prompt:'优先关注哪项内容？',description:'可以跳过这道问题。',choices:[{value:'content',label:'作品内容'},{value:'evidence',label:'审核证据'}]}];return <div className="flex flex-col gap-4"><Questionnaire items={questions} onSubmit={e=>{e.preventDefault();setQResult('回答已记录在当前页面，未发送。')}}><QuestionnaireProgress/>{questions.map(q=><QuestionnaireItem key={q.name} name={q.name} required={q.required}><QuestionnaireTitle>{q.prompt}</QuestionnaireTitle><QuestionnaireDescription>{q.description}</QuestionnaireDescription><QuestionnaireChoices>{q.choices.map(o=><QuestionnaireChoice key={o.value} value={o.value}>{o.label}</QuestionnaireChoice>)}</QuestionnaireChoices><QuestionnaireError/></QuestionnaireItem>)}<QuestionnaireActions><QuestionnairePrevious>上一步</QuestionnairePrevious><QuestionnaireSkip>跳过</QuestionnaireSkip><QuestionnaireNext>下一步</QuestionnaireNext><QuestionnaireSubmit>完成</QuestionnaireSubmit></QuestionnaireActions></Questionnaire><p role="status">{qResult}</p></div>}
    case 'typography':return <div className="flex flex-col gap-6"><h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight text-balance">Typography</h1><p className="leading-7">文字示例采用官方 Typeset / Typography 文档提供的排版实用类。字体仍是 Nova 初始化的 Geist；中文使用系统回退。</p><h3 className="scroll-m-20 text-2xl font-semibold tracking-tight">清楚的作品要求</h3><blockquote className="border-l-2 pl-6 italic">审核通过不等于银行到账。</blockquote><p className="text-sm text-muted-foreground">这是一项官方排版模式，不是单独生成的 UI 组件。</p></div>
    default:return null
  }
}

function FieldExample(){
 const [title,setTitle]=useState(''),[email,setEmail]=useState(''),[note,setNote]=useState(''),[errors,setErrors]=useState<Record<string,string>>({}),[phase,setPhase]=useState('idle'),[failed,setFailed]=useState(false)
 const titleRef=useRef<HTMLInputElement>(null),emailRef=useRef<HTMLInputElement>(null),submitRef=useRef<HTMLButtonElement>(null)
 async function submit(e:FormEvent){e.preventDefault();if(phase==='busy')return;const next:Record<string,string>={};if(!title.trim())next.title='请输入作品标题。';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))next.email='请输入完整邮箱，例如 name@example.com。';setErrors(next);if(Object.keys(next).length){(next.title?titleRef:emailRef).current?.focus();return;}setPhase('busy');await new Promise(r=>setTimeout(r,650));setPhase(failed?'success':'error');setFailed(true);requestAnimationFrame(()=>{if(document.activeElement===document.body)submitRef.current?.focus()})}
 return <form onSubmit={submit} noValidate><FieldGroup><Field data-invalid={!!errors.title}><FieldLabel htmlFor="form-title">作品标题</FieldLabel><Input ref={titleRef} id="form-title" value={title} onChange={e=>setTitle(e.target.value)} aria-invalid={!!errors.title} aria-describedby={errors.title?'form-title-error':undefined}/>{errors.title&&<FieldError id="form-title-error">{errors.title}</FieldError>}</Field><Field data-invalid={!!errors.email}><FieldLabel htmlFor="form-email">通知邮箱</FieldLabel><Input ref={emailRef} id="form-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} aria-invalid={!!errors.email} aria-describedby={errors.email?'form-email-error':undefined}/>{errors.email&&<FieldError id="form-email-error">{errors.email}</FieldError>}</Field><Field><FieldLabel htmlFor="form-note">补充说明</FieldLabel><Textarea id="form-note" value={note} onChange={e=>setNote(e.target.value)}/><FieldDescription>第一次请求模拟失败，重试成功；没有外部网络请求。</FieldDescription></Field>{phase==='error'&&<Alert variant="destructive"><AlertCircleIcon/><AlertTitle>保存失败，内容已保留</AlertTitle><AlertDescription>模拟服务暂时不可用，请重试。不会清空标题、邮箱或说明。</AlertDescription></Alert>}{phase==='success'&&<Alert><CheckIcon/><AlertTitle>说明已保存</AlertTitle><AlertDescription>仅在当前页面保存，刷新后重置。</AlertDescription></Alert>}<Field><Button ref={submitRef} id="form-submit" type="submit" disabled={phase==='busy'} aria-busy={phase==='busy'}>{phase==='busy'&&<Spinner data-icon="inline-start"/>}{phase==='busy'?'正在保存…':phase==='error'?'重试保存':'保存说明'}</Button></Field></FieldGroup></form>
}
